import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,it,expect,vi} from 'vitest';
import {ResearchDemoRequests} from '@/components/customer/research-demo-requests';
import type {ResearchDemoPort,ResearchDemoRequest} from '@/lib/infrastructure/supabase/research-demo-adapter';
afterEach(cleanup);
function fixture(status:ResearchDemoRequest['status']='pending_review'):ResearchDemoRequest{return {id:'demo-request-1',ownerId:'customer-1',revisionId:'revision-1',status,createdAt:'2026-09-16T01:00:00Z',notes:null,quotes:[],history:[],request:{startAt:'2026-10-20T08:00:00+07:00',partySize:2} as ResearchDemoRequest['request'],plan:{stops:[{id:'mapped-id',name:'Điểm demo',address:'TP.HCM',arrival:'08:30',departure:'09:30'}],durationMinutes:120,totalVnd:500000} as ResearchDemoRequest['plan']};}
function port(rows:ResearchDemoRequest[]):ResearchDemoPort{return {listAdmin:vi.fn(async()=>rows),listCustomer:vi.fn(async()=>rows),submit:vi.fn(),decide:vi.fn(async()=>{}),createQuote:vi.fn(async()=>'quote-1')};}
async function open(){fireEvent.click(await screen.findByRole('button',{name:'Xem chi tiết'}));}
it('requires a note for changes or rejection without sending invalid decisions',async()=>{const p=port([fixture()]);render(<ResearchDemoRequests port={p} admin/>);await open();fireEvent.click(screen.getByRole('button',{name:'Yêu cầu chỉnh sửa'}));fireEvent.click(screen.getByRole('button',{name:'Gửi yêu cầu chỉnh sửa'}));expect(p.decide).not.toHaveBeenCalled();expect(screen.getByRole('alert')).toHaveTextContent('Vui lòng nhập ghi chú');fireEvent.change(screen.getByLabelText('Ghi chú / Lý do'),{target:{value:'Xin đổi giờ bắt đầu'}});fireEvent.click(screen.getByRole('button',{name:'Gửi yêu cầu chỉnh sửa'}));await waitFor(()=>expect(p.decide).toHaveBeenCalledWith('demo-request-1','changes_requested','Xin đổi giờ bắt đầu'));});
it('does not offer quote creation for pending requests',async()=>{render(<ResearchDemoRequests port={port([fixture()])} admin/>);await open();expect(screen.queryByRole('button',{name:'Lập báo giá'})).toBeNull();});
it('creates a final quote only for an approved request and reloads persisted data',async()=>{const p=port([fixture('approved')]);render(<ResearchDemoRequests port={p} admin/>);await open();fireEvent.click(screen.getByRole('button',{name:'Lập báo giá'}));fireEvent.change(screen.getByLabelText('Số tiền báo giá demo'),{target:{value:'750000'}});fireEvent.click(screen.getByRole('button',{name:/Chọn điều kiện báo giá/}));fireEvent.click(screen.getByRole('button',{name:'Xong'}));fireEvent.click(screen.getByRole('button',{name:'Tạo và phát hành báo giá'}));await waitFor(()=>expect(p.createQuote).toHaveBeenCalledWith('demo-request-1',{title:'Báo giá tour cá nhân hóa',amount:750000,currency:'VND',conditions:'- Không bao gồm: Chi phí cá nhân\n- Không bao gồm: Dịch vụ phát sinh'}));expect(p.listAdmin).toHaveBeenCalledTimes(2);expect(screen.getByRole('status')).toHaveTextContent('Khách có thể xem báo giá');});
it('loads customer-only data and displays notes and persisted quote after reload',async()=>{const row=fixture('approved');row.notes='Đã kiểm tra lịch trình';row.quotes=[{id:'quote-demo',title:'Báo giá đã lưu',amount:750000,currency:'VND',conditions:'Dịch vụ mô phỏng',createdAt:'2026-09-16T01:00:00Z',expiresAt:'2026-09-18T01:00:00Z',status:'active'}];const p=port([row]);render(<ResearchDemoRequests port={p}/>);await open();expect(p.listAdmin).not.toHaveBeenCalled();expect(screen.getByText('Báo giá đã lưu')).toBeVisible();expect(screen.getByText(/Đã kiểm tra lịch trình/)).toBeVisible();expect(screen.queryByRole('button',{name:'Duyệt'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Làm mới'}));await waitFor(()=>expect(p.listCustomer).toHaveBeenCalledTimes(2));expect(screen.getByText('Báo giá đã lưu')).toBeVisible();});
it('shows load failure rather than a false empty state',async()=>{const p=port([]);p.listCustomer=vi.fn(async()=>{throw Error('network');});render(<ResearchDemoRequests port={p}/>);expect(await screen.findByRole('alert')).toHaveTextContent('Không thể tải');expect(screen.queryByText('Chưa có yêu cầu tour cá nhân hóa.')).toBeNull();});
it('links a customer pending quote to the dedicated personalized payment page',async()=>{const base=fixture('approved');const row={...base,request:{...base.request,startAt:new Date(Date.now()+86400000*5).toISOString()},quotes:[{id:'quote-pending',title:'Báo giá chờ thanh toán',amount:750000,currency:'VND' as const,conditions:'Demo',createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+86400000).toISOString(),status:'checkout_pending' as const}]};render(<ResearchDemoRequests port={port([row])}/>);const link=await screen.findByRole('link',{name:'Thanh toán'});expect(link).toHaveAttribute('href','/vi/personalized-payment?request=demo-request-1&quote=quote-pending');});

it('approves without automatically creating a quote and allows quoting afterward',async()=>{const row=fixture();const p=port([row]);p.decide=vi.fn(async()=>{row.status='approved';});render(<ResearchDemoRequests port={p} admin/>);await open();fireEvent.click(screen.getByRole('button',{name:'Duyệt'}));await waitFor(()=>expect(p.decide).toHaveBeenCalledWith('demo-request-1','approved',''));expect(screen.queryByText('Xác nhận xử lý')).toBeNull();await screen.findByRole('button',{name:'Lập báo giá'});expect(p.createQuote).not.toHaveBeenCalled();expect(screen.queryByRole('button',{name:'Duyệt'})).toBeNull();});
it('filters quoted requests and searches by quote title in the combined screen',async()=>{const quoted=fixture('approved');quoted.id='quoted-request';quoted.quotes=[{id:'q-1',title:'Tour riêng tháng mười',amount:100000,currency:'VND',conditions:'Demo',createdAt:'2026-09-20',expiresAt:'2026-09-22',status:'active'}];render(<ResearchDemoRequests port={port([fixture(),quoted])} admin initialView="quotes"/>);await screen.findByText('quoted-r');expect(screen.queryByText('demo-req')).toBeNull();fireEvent.change(screen.getByLabelText('Tìm yêu cầu'),{target:{value:'Tour riêng tháng mười'}});expect(screen.getByText('quoted-r')).toBeVisible();});

it('submits rejection with a required reason without a separate confirmation',async()=>{const p=port([fixture()]);render(<ResearchDemoRequests port={p} admin/>);await open();fireEvent.click(screen.getByRole('button',{name:'Từ chối'}));fireEvent.click(screen.getByRole('button',{name:'Gửi từ chối'}));expect(p.decide).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('Ghi chú / Lý do'),{target:{value:'Lịch trình không khả thi'}});fireEvent.click(screen.getByRole('button',{name:'Gửi từ chối'}));await waitFor(()=>expect(p.decide).toHaveBeenCalledWith('demo-request-1','rejected','Lịch trình không khả thi'));expect(screen.queryByText('Xác nhận xử lý')).toBeNull();});

it('expands details immediately below the selected row and collapses them on a second click',async()=>{const second={...fixture(),id:'second-request'};render(<ResearchDemoRequests port={port([fixture(),second])}/>);const buttons=await screen.findAllByRole('button',{name:'Xem chi tiết'});fireEvent.click(buttons[0]);const region=screen.getByRole('region');expect(buttons[0]).toHaveAttribute('aria-expanded','true');expect(buttons[0].closest('tr')?.nextElementSibling).toContainElement(region);fireEvent.click(buttons[1]);expect(buttons[0]).toHaveAttribute('aria-expanded','false');expect(buttons[1].closest('tr')?.nextElementSibling).toContainElement(screen.getByRole('region'));fireEvent.click(buttons[1]);expect(screen.queryByRole('region')).toBeNull();});

it('opens a readable admin workspace with tabs and preserves list filters on return',async()=>{render(<ResearchDemoRequests port={port([fixture()])} admin/>);fireEvent.change(screen.getByLabelText('Tìm yêu cầu'),{target:{value:'demo'}});await open();expect(screen.queryByRole('table')).toBeNull();expect(screen.getByRole('tab',{name:'Nhu cầu khách'})).toHaveAttribute('aria-selected','true');expect(screen.getByText('Nhu cầu của khách')).toBeVisible();fireEvent.click(screen.getByRole('tab',{name:'Lịch trình'}));expect(screen.getByText('Nhu cầu của khách')).not.toBeVisible();expect(screen.getByText(/08:30 – 09:30/)).toBeVisible();fireEvent.keyDown(screen.getByRole('tab',{name:'Lịch trình'}),{key:'ArrowRight'});expect(screen.getByRole('tab',{name:'Báo giá'})).toHaveFocus();expect(screen.getByText('Chưa có báo giá cho yêu cầu này.')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'← Danh sách yêu cầu'}));expect(screen.getByLabelText('Tìm yêu cầu')).toHaveValue('demo');expect(screen.getByRole('table')).toBeVisible();});
it('shows five customer requests per page and paginates the remaining requests',async()=>{const rows=Array.from({length:7},(_,index)=>({...fixture(),id:`request-${index+1}`}));render(<ResearchDemoRequests port={port(rows)}/>);expect(await screen.findByText('Hiển thị 1–5 trong 7 yêu cầu')).toBeVisible();expect(screen.getAllByRole('button',{name:'Xem chi tiết'})).toHaveLength(5);fireEvent.click(screen.getByRole('button',{name:'Trang sau'}));expect(await screen.findByText('Hiển thị 6–7 trong 7 yêu cầu')).toBeVisible();expect(screen.getAllByRole('button',{name:'Xem chi tiết'})).toHaveLength(2);});
