import {reviewedDataset} from '@/components/dev/reviewed-tours';
import {reviewedDepartures} from '@/components/dev/reviewed-departures';
import {tourIllustration} from '@/lib/domain/data/tour-illustrations';
import {AdminTourError,activeDepartures,type AdminTour,type AdminToursPort,type TourContent,type TourDeparture,type TourVersion} from '@/lib/application/admin-tours';
export const blankTour:TourContent={name:'',nameEn:'',description:'',descriptionEn:'',category:'Ẩm thực',pickup:'',pickupEn:'',duration:180,price:0,languages:'Tiếng Việt, Tiếng Anh',imageUrl:'',itinerary:'',itineraryEn:'',included:'',includedEn:'',excluded:'',excludedEn:'',cancellation:'',cancellationEn:'',sourceUrl:''};
function displayDate(startAt:string){return new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(startAt));}
function scheduleFor(t:typeof reviewedDataset.tours[number],i:number):TourDeparture[]{
 const source=t.departures[0];
 if(!source)return [];
 return reviewedDepartures(source,i).map((departure,index)=>({
  id:i===0&&index===0?'departure-1':i===0&&index===1?'departure-2':departure.id,
  date:displayDate(departure.startAt),
  status:i===0&&index===1?'sold_out':'scheduled',
 }));
}
 function initial():AdminTour[]{return reviewedDataset.tours.map((t,i)=>{const v:TourVersion={...blankTour,version:1,name:t.translations.vi.title,nameEn:t.translations.en.title,description:t.translations.vi.summary,descriptionEn:t.translations.en.summary,category:'Lịch sử & văn hóa',pickup:t.translations.vi.meetingPoint,pickupEn:t.translations.en.meetingPoint,duration:t.durationMinutes,price:t.priceVndPerPerson,languages:'Tiếng Việt, Tiếng Anh',imageUrl:t.slug.includes('waterways')?'/images/green/saigon-skyline.webp':tourIllustration(t.slug).src,itinerary:t.stopPlaceIds.map(id=>reviewedDataset.places.find(p=>p.id===id)?.translations.vi.title??'').join('\n'),itineraryEn:t.stopPlaceIds.map(id=>reviewedDataset.places.find(p=>p.id===id)?.translations.en.title??'').join('\n'),included:t.inclusions.join('; '),includedEn:t.englishInclusions.join('; '),excluded:t.exclusions.join('; '),excludedEn:t.englishExclusions.join('; '),cancellation:t.cancellationPolicy,cancellationEn:t.englishCancellationPolicy,sourceUrl:'https://localens-ashen.vercel.app/vi/tours/'+t.slug+'/'};return {id:t.id,status:i===1?'draft':'published',published:i===1?null:v,draft:i===1?v:null,history:[],departures:i===0?[{id:'departure-1',date:'2026-10-03 08:30',status:'scheduled'},{id:'departure-2',date:'2026-10-10 08:30',status:'sold_out'}]:[],calendarDepartures:scheduleFor(t,i),updatedAt:'2026-09-14T00:00:00.000Z'};});}
function basic(d:TourContent){if(!d.name.trim())throw new AdminTourError('Vui lòng nhập tên tour','name');if(!Number.isFinite(d.price)||d.price<0)throw new AdminTourError('Giá phải là số không âm','price');if(!Number.isFinite(d.duration)||d.duration<=0)throw new AdminTourError('Thời lượng phải lớn hơn 0','duration');if(d.imageUrl&&!/^\/(?!\/)[^\\\s]*$|^https?:\/\/[^\s]+$/i.test(d.imageUrl))throw new AdminTourError('Dùng đường dẫn ảnh nội bộ hoặc URL HTTPS/HTTP','imageUrl');}
function publishable(d:TourContent){basic(d);for(const [k,v] of Object.entries(d)){if(typeof v==='string'&&!v.trim())throw new AdminTourError('Vui lòng bổ sung đầy đủ thông tin và nội dung Việt/Anh trước khi xuất bản',k as keyof TourContent);}try{const u=new URL(d.sourceUrl);if(!['https:','http:'].includes(u.protocol))throw new Error();}catch{throw new AdminTourError('Nguồn thông tin phải là URL HTTP/HTTPS hợp lệ','sourceUrl');}}
export function createDemoAdminToursPort(hasActiveDepartures?:(id:string)=>boolean):AdminToursPort{
 let rows=initial();let next=6;
 const find=(id:string)=>{const t=rows.find(t=>t.id===id);if(!t)throw new AdminTourError('Không thể tải thông tin tour. Vui lòng thử lại sau');return t;};
 return {async list(){return structuredClone(rows);},async save(data,id){basic(data);const copy=structuredClone(data);if(id){const t=find(id);t.draft={...copy,version:t.draft?.version??Math.max(t.published?.version??0,...t.history.map(v=>v.version))+1};t.updatedAt=new Date().toISOString();}else rows=[...rows,{id:`tour-demo-${next++}`,status:'draft',published:null,draft:{...copy,version:1},history:[],departures:[],updatedAt:new Date().toISOString()}];},async publish(id){const t=find(id);const v=t.draft??t.published;if(!v)throw new AdminTourError('Không có phiên bản để xuất bản');publishable(v);if(t.draft){if(t.published)t.history.push(structuredClone(t.published));t.published=structuredClone(t.draft);t.draft=null;}t.status='published';t.updatedAt=new Date().toISOString();},async archive(id){const t=find(id);if(t.status!=='published')throw new AdminTourError('Chỉ tour đã xuất bản mới có thể lưu trữ');if(hasActiveDepartures?hasActiveDepartures(id):activeDepartures(t).length)throw new AdminTourError('Không thể lưu trữ. Vui lòng xử lý các lịch khởi hành Đã lên lịch hoặc Đã hết chỗ trước.');t.status='archived';t.updatedAt=new Date().toISOString();}};
}
