export const API_ERROR_CODES = [
  "INVALID_REQUEST",
  "UNKNOWN_FIELD",
  "UNSAFE_MONEY",
  "UNSAFE_TIME",
  "UNKNOWN_AREA_ID",
  "UNKNOWN_PLACE_ID",
  "UNKNOWN_REQUIREMENT_ID",
  "UNKNOWN_EXPERIENCE_TYPE",
  "INVALID_FILTER",
  "INTERNAL_ERROR",
  "INVALID_ITINERARY_INPUT",
  "USD_DISABLED",
  "NO_FEASIBLE_ITINERARY",
  "ITINERARY_SEARCH_LIMIT",
  "INVALID_ITINERARY_RESULT",
] as const;
export type ApiErrorCode = (typeof API_ERROR_CODES)[number];

export const API_MESSAGE_KEYS = {
  localeInvalid: "api.locale.invalid",
  requestInvalid: "api.request.invalid",
  requestUnknownField: "api.request.unknown_field",
  moneyUnsafe: "api.money.unsafe",
  timeUnsafe: "api.time.unsafe",
  internal: "api.internal",
  areaUnknown: "api.area.unknown",
  placeUnknown: "api.place.unknown",
  requirementUnknown: "api.requirement.unknown",
  filterInvalid: "api.filter.invalid",
  filterUnknownField: "api.filter.unknown_field",
  filterKeywordInvalid: "api.filter.keyword.invalid",
  filterAreaInvalid: "api.filter.area.invalid",
  filterAreaUnknown: "api.filter.area.unknown",
  filterExperienceTypeInvalid: "api.filter.experience_type.invalid",
  filterExperienceTypeUnknown: "api.filter.experience_type.unknown",
  itineraryInvalid: "api.itinerary.invalid",
  itineraryUsdDisabled: "api.itinerary.usd_disabled",
  itineraryNoFeasible: "api.itinerary.no_feasible",
  itinerarySearchLimit: "api.itinerary.search_limit",
} as const;
export type ApiMessageKey = (typeof API_MESSAGE_KEYS)[keyof typeof API_MESSAGE_KEYS];

export const API_MESSAGE_CATALOG: Record<"en" | "vi", Record<ApiMessageKey, string>> = {
  en: {
    "api.locale.invalid": "Choose English or Vietnamese.",
    "api.request.invalid": "The request is invalid.",
    "api.request.unknown_field": "This field is not accepted.",
    "api.money.unsafe": "The money amount is outside the safe range.",
    "api.time.unsafe": "The time value is invalid or unsafe.",
    "api.internal": "The demo service is temporarily unavailable.",
    "api.area.unknown": "Choose an area from the LocalLens catalog.",
    "api.place.unknown": "Choose a place from the LocalLens catalog.",
    "api.requirement.unknown": "Choose a supported structured requirement.",
    "api.filter.invalid": "The tour filter is invalid.",
    "api.filter.unknown_field": "This filter field is not accepted.",
    "api.filter.keyword.invalid": "The keyword is invalid.",
    "api.filter.area.invalid": "The area filter is invalid.",
    "api.filter.area.unknown": "Choose an area from the LocalLens catalog.",
    "api.filter.experience_type.invalid": "The experience type filter is invalid.",
    "api.filter.experience_type.unknown": "Choose a supported experience type.",
    "api.itinerary.invalid": "The itinerary request could not be processed.",
    "api.itinerary.usd_disabled": "USD planning is unavailable in the demo sample.",
    "api.itinerary.no_feasible": "No feasible itinerary matches these requirements.",
    "api.itinerary.search_limit": "The itinerary search limit was reached; retry later.",
  },
  vi: {
    "api.locale.invalid": "Hãy chọn English hoặc Tiếng Việt.",
    "api.request.invalid": "Yêu cầu không hợp lệ.",
    "api.request.unknown_field": "Trường này không được chấp nhận.",
    "api.money.unsafe": "Số tiền nằm ngoài giới hạn an toàn.",
    "api.time.unsafe": "Giá trị thời gian không hợp lệ hoặc không an toàn.",
    "api.internal": "Dịch vụ demo tạm thời không khả dụng.",
    "api.area.unknown": "Hãy chọn khu vực trong danh mục LocalLens.",
    "api.place.unknown": "Hãy chọn địa điểm trong danh mục LocalLens.",
    "api.requirement.unknown": "Hãy chọn yêu cầu có cấu trúc được hỗ trợ.",
    "api.filter.invalid": "Bộ lọc tour không hợp lệ.",
    "api.filter.unknown_field": "Trường bộ lọc này không được chấp nhận.",
    "api.filter.keyword.invalid": "Từ khóa không hợp lệ.",
    "api.filter.area.invalid": "Bộ lọc khu vực không hợp lệ.",
    "api.filter.area.unknown": "Hãy chọn khu vực trong danh mục LocalLens.",
    "api.filter.experience_type.invalid": "Bộ lọc nhóm trải nghiệm không hợp lệ.",
    "api.filter.experience_type.unknown": "Hãy chọn nhóm trải nghiệm được hỗ trợ.",
    "api.itinerary.invalid": "Không thể xử lý yêu cầu lịch trình.",
    "api.itinerary.usd_disabled": "Lập lịch bằng USD chưa khả dụng trong dữ liệu demo.",
    "api.itinerary.no_feasible": "Không có lịch trình khả thi với các yêu cầu này.",
    "api.itinerary.search_limit": "Đã đạt giới hạn tìm kiếm lịch trình; hãy thử lại sau.",
  },
};
