'use client';
import {useEffect,useRef,useState} from 'react';
import {Trash2,X} from 'lucide-react';
import type {Locale} from '@/lib/i18n/config';
import type {ReviewedBooking,ReviewedBookings} from '@/lib/infrastructure/supabase/reviewed-bookings';
import styles from './cancel-booking-dialog.module.css';
export function CancelBookingDialog({locale,booking,service,onClose,onCancelled}:{locale:Locale;booking:ReviewedBooking;service:ReviewedBookings;onClose:()=>void;onCancelled:(row:ReviewedBooking)=>void}){
 const dialog=useRef<HTMLDialogElement>(null),lock=useRef(false);const [busy,setBusy]=useState(false),[error,setError]=useState('');const vi=locale==='vi';
 useEffect(()=>{const node=dialog.current;const focus=document.activeElement as HTMLElement|null;node?.showModal();return()=>{node?.close();if(focus?.isConnected)focus.focus();};},[]);
 async function cancel(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const saved=await service.cancel(booking.id);onCancelled(saved);window.dispatchEvent(new Event('localens-bookings-changed'));onClose();}catch(e){setError(e instanceof Error&&e.message.includes('CANCEL_NOT_ALLOWED')?(vi?'Đơn không còn đủ điều kiện hủy. Chỉ có thể hủy trước giờ khởi hành ít nhất 48 giờ.':'Cancellation is only available at least 48 hours before departure.'):(vi?'Chưa thể hủy đơn. Vui lòng thử lại.':'Unable to cancel your booking. Please try again.'));}finally{lock.current=false;setBusy(false);}}
 return <dialog ref={dialog} className={styles.dialog} aria-labelledby="cancel-booking-title" aria-describedby="cancel-booking-description" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><button className={styles.close} aria-label={vi?'Đóng':'Close'} disabled={busy} onClick={onClose}><X size={20}/></button><div className={styles.icon}><Trash2 size={28}/></div><h2 id="cancel-booking-title">{vi?'Xác nhận hủy đơn':'Cancel booking?'}</h2><p id="cancel-booking-description">{vi?'Bạn có chắc chắn muốn hủy đơn này không? Sau khi hủy, chỗ đã đặt sẽ được trả lại.':'Are you sure you want to cancel this booking? Your reserved places will be released.'}</p><small>{vi?'Hủy đơn không đồng nghĩa đã hoàn tiền.':'Cancellation does not mean a refund has been issued.'}</small>{error&&<p className={styles.error} role="alert">{error}</p>}<div className={styles.actions}><button className={styles.danger} disabled={busy} onClick={()=>void cancel()}>{busy?(vi?'Đang hủy…':'Cancelling…'):(vi?'Hủy đơn':'Cancel booking')}</button><button autoFocus disabled={busy} onClick={onClose}>{vi?'Quay lại':'Go back'}</button></div></dialog>;
}
