'use client';
import {useEffect,useRef,useState} from 'react';
import {Star,X} from 'lucide-react';
import type {Locale} from '@/lib/i18n/config';
import type {ReviewedBooking,ReviewedBookings} from '@/lib/infrastructure/supabase/reviewed-bookings';
import styles from './review-tour-dialog.module.css';
export function ReviewTourDialog({locale,booking,service,onClose,onSaved}:{locale:Locale;booking:ReviewedBooking;service:ReviewedBookings;onClose:()=>void;onSaved:(row:ReviewedBooking)=>void}){
 const vi=locale==='vi',dialog=useRef<HTMLDialogElement>(null),lock=useRef(false);
 const [row,setRow]=useState(booking),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[rating,setRating]=useState(0),[body,setBody]=useState('');
 useEffect(()=>{let alive=true;const focus=document.activeElement as HTMLElement|null;dialog.current?.showModal();void service.get(booking.id).then(saved=>{if(alive){setRow(saved);setLoading(false);}}).catch(()=>{if(alive){setError(vi?'Không thể tải thông tin đơn. Vui lòng đóng và thử lại.':'Unable to load this booking. Please close and try again.');}});return()=>{alive=false;dialog.current?.close();if(focus?.isConnected)focus.focus();};},[booking.id,service,vi]);
 const allowed=row.status==='completed'&&!row.reviewed_at;
 async function submit(){if(lock.current||loading||!allowed)return;
 if(!Number.isInteger(rating)||rating<1||rating>5){setError(vi?'Vui lòng chọn mức độ hài lòng từ 1–5 sao':'Please select a rating from 1 to 5 stars');return;}
 if(!body.trim()||body.trim().length>2000){setError(vi?'Vui lòng nhập nội dung đánh giá, tối đa 2.000 ký tự':'Please enter a review of up to 2,000 characters');return;}
 lock.current=true;setBusy(true);setError('');try{const saved=await service.review(row.id,rating,body.trim());onSaved(saved);window.dispatchEvent(new Event('localens-bookings-changed'));window.dispatchEvent(new Event('localens-reviews-changed'));onClose();}catch(e){setError(e instanceof Error&&e.message.includes('REVIEW_NOT_ALLOWED')?(vi?'Tour này chưa hoàn thành hoặc bạn đã thực hiện đánh giá trước đó':'This tour is not completed or has already been reviewed'):(vi?'Đã có lỗi xảy ra. Chưa thể gửi đánh giá, vui lòng thử lại sau':'Unable to submit your review. Please try again later'));}finally{lock.current=false;setBusy(false);}}
 return <dialog ref={dialog} className={styles.dialog} aria-labelledby="review-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><button className={styles.close} aria-label={vi?'Đóng':'Close'} disabled={busy} onClick={onClose}><X size={20}/></button><h2 id="review-title">{row.reviewed_at?(vi?'Đánh giá của bạn':'Your review'):(vi?'Chia sẻ trải nghiệm của bạn':'Share your experience')}</h2>
 {loading&&!error&&<p role="status">{vi?'Đang kiểm tra thông tin đơn…':'Checking booking…'}</p>}{error&&<p role="alert" className={styles.error}>{error}</p>}
 {!loading&&(row.reviewed_at?<><p className={styles.stars}>{row.rating} / 5 ★</p><p className={styles.body}>{row.review_text}</p></>:!allowed?<p role="alert">{vi?'Tour này chưa hoàn thành hoặc bạn đã thực hiện đánh giá trước đó':'This tour is not completed or has already been reviewed'}</p>:<form onSubmit={e=>{e.preventDefault();void submit();}}><fieldset disabled={busy}><legend>{vi?'Bạn hài lòng với chuyến đi ở mức nào?':'How was your trip?'}</legend><div className={styles.stars} role="group" aria-label={vi?'Điểm đánh giá':'Rating'}>{[1,2,3,4,5].map(n=><button type="button" key={n} aria-label={`${n} ${vi?'sao':'stars'}`} aria-pressed={rating===n} onClick={()=>{setRating(n);setError('');}}><Star size={32} fill={n<=rating?'currentColor':'none'}/></button>)}</div><label>{vi?'Nội dung đánh giá':'Your review'}<textarea rows={5} maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} placeholder={vi?'Điều gì khiến chuyến đi đáng nhớ với bạn?':'What made your trip memorable?'}/></label><small>{body.length}/2.000</small><p>{vi?'Đánh giá sẽ được đăng công khai. Vui lòng không ghi số điện thoại hoặc thông tin riêng tư.':'Your review will be public. Please leave out phone numbers and private information.'}</p><div className={styles.actions}><button type="button" onClick={onClose}>{vi?'Quay lại':'Go back'}</button><button type="submit">{busy?(vi?'Đang gửi…':'Sending…'):(vi?'Gửi đánh giá':'Submit review')}</button></div></fieldset></form>)}</dialog>;
}
