import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,cleanup} from '@testing-library/react';
import {ReviewTourDialog} from '@/components/customer/review-tour-dialog';
import type {ReviewedBooking,ReviewedBookings} from '@/lib/infrastructure/supabase/reviewed-bookings';
beforeEach(()=>{HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};});afterEach(cleanup);
const row={id:'owned',status:'completed'} as ReviewedBooking;
async function setup(review=vi.fn(),saved=row){const onClose=vi.fn(),onSaved=vi.fn();render(<ReviewTourDialog locale="vi" booking={row} service={{get:vi.fn().mockResolvedValue(saved),review} as unknown as ReviewedBookings} onClose={onClose} onSaved={onSaved}/>);await vi.waitFor(()=>expect(screen.queryByText('Đang kiểm tra thông tin đơn…')).toBeNull());return {review,onClose,onSaved};}
it('requires an explicit star selection and nonempty content',async()=>{const x=await setup();fireEvent.click(screen.getByText('Gửi đánh giá'));expect(await screen.findByRole('alert')).toHaveTextContent('1–5 sao');fireEvent.click(screen.getByRole('button',{name:'4 sao'}));fireEvent.click(screen.getByText('Gửi đánh giá'));expect(await screen.findByRole('alert')).toHaveTextContent('nội dung');expect(x.review).not.toHaveBeenCalled();});
it('preserves input on save failure',async()=>{const x=await setup(vi.fn().mockRejectedValue(Error('network')));fireEvent.click(screen.getByRole('button',{name:'4 sao'}));fireEvent.change(screen.getByRole('textbox'),{target:{value:'Chuyến đi đáng nhớ'}});fireEvent.click(screen.getByText('Gửi đánh giá'));await screen.findByRole('alert');expect(screen.getByRole('textbox')).toHaveValue('Chuyến đi đáng nhớ');expect(x.onClose).not.toHaveBeenCalled();});
it('saves once and closes after the persisted response',async()=>{const saved={...row,rating:4,review_text:'Rất tốt',reviewed_at:new Date().toISOString()};const x=await setup(vi.fn().mockResolvedValue(saved));fireEvent.click(screen.getByRole('button',{name:'4 sao'}));fireEvent.change(screen.getByRole('textbox'),{target:{value:'Rất tốt'}});fireEvent.click(screen.getByText('Gửi đánh giá'));await vi.waitFor(()=>expect(x.onSaved).toHaveBeenCalledWith(saved));expect(x.review).toHaveBeenCalledExactlyOnceWith('owned',4,'Rất tốt');expect(x.onClose).toHaveBeenCalledOnce();});
it('does not allow an incomplete booking',async()=>{const x=await setup(vi.fn(),{...row,status:'confirmed'});expect(screen.queryByRole('textbox')).toBeNull();expect(await screen.findByRole('alert')).toHaveTextContent('chưa hoàn thành');expect(x.review).not.toHaveBeenCalled();});
it('shows a submitted review without an editable form',async()=>{await setup(vi.fn(),{...row,rating:5,review_text:'Tuyệt vời',reviewed_at:new Date().toISOString()});expect(screen.getByText('Tuyệt vời')).toBeInTheDocument();expect(screen.queryByText('Gửi đánh giá')).toBeNull();});
it('closes without writing on cancel',async()=>{const x=await setup();fireEvent.click(screen.getByText('Quay lại'));expect(x.onClose).toHaveBeenCalledOnce();expect(x.review).not.toHaveBeenCalled();});
