import type { Locale } from "@/lib/i18n/config";

export const PORTAL_COPY = {
  en: {
    brand: "LocalLens",
    eyebrow: "Your LocalLens space",
    overview: "Overview",
    demoOnly: "Demo-only",
    demoNotice:
      "This portal uses seeded demo identities and browser session data. It is not production authentication, security, or persistence.",
    loading: "Loading your portal…",
    loadingData: "Loading portal data…",
    retry: "Try again",
    errorTitle: "We could not load this portal",
    errorMessage: "The demo fixture may be unavailable or invalid. Try again to reload the seeded data.",
    chooseIdentity: "Choose a demo identity",
    signInHeading: "Sign in to your demo account",
    signInIntro:
      "Select a seeded identity to explore the customer, guide, or administrator experience.",
    signInDisclosure:
      "Demo sign-in is a local UX boundary only. It does not verify a real account or protect production data.",
    continueAs: "Continue as",
    signedInAs: "Signed in as",
    customer: "Customer",
    guide: "Guide",
    admin: "Administrator",
    accountPortal: "Customer portal",
    guidePortal: "Guide portal",
    adminPortal: "Admin portal",
    accountNav: "Account",
    guideNav: "Guide space",
    adminNav: "Admin space",
    signOut: "Sign out",
    accessDeniedTitle: "Customer portal unavailable",
    guideAccessDeniedTitle: "Guide portal unavailable",
    adminAccessDeniedTitle: "Admin portal unavailable",
    accessDeniedMessage: "This route is limited to the signed-in role.",
    signedInAsRole: "You are signed in as a",
    openYourPortal: "Open your portal",
    customerHeading: "Your customer portal",
    customerIntro: "Keep your details, bookings, and requests together in one place.",
    profileHeading: "Your profile",
    profileIntro: "Only the fields below are editable in this demo.",
    fullName: "Full name",
    nationality: "Nationality",
    email: "Email",
    phone: "Phone",
    language: "Language",
    english: "English",
    vietnamese: "Vietnamese",
    saveProfile: "Save profile",
    saving: "Saving…",
    profileSaved: "Profile saved in this demo session.",
    profileError: "We could not save your profile.",
    bookingsHeading: "Your bookings",
    bookingsIntro: "Track booking and payment states separately.",
    noBookings: "You have no bookings in this demo account.",
    bookingStatus: "Booking status",
    paymentStatus: "Payment status",
    partySize: "Party size",
    meetingPoint: "Meeting point",
    date: "Date",
    created: "Created",
    paid: "Paid",
    paymentPending: "Payment pending",
    paymentNotAvailable: "Payment state unavailable",
    total: "Total",
    simulatedPayment: "Payment is simulated for this thesis demo; no card details or real charge are collected.",
    cancellationHeading: "Cancellation request",
    requestCancellation: "Request cancellation",
    cancellationReason: "Cancellation reason",
    cancellationReasonHint: "Tell the administrator why you need to cancel.",
    sendCancellation: "Send cancellation request",
    cancelForm: "Close form",
    cancellationPending: "Cancellation request pending administrator decision.",
    cancellationApproved: "Cancellation approved by administrator.",
    cancellationRejected: "Cancellation request rejected by administrator.",
    cancellationSent: "Cancellation request sent.",
    cancellationError: "We could not send the cancellation request.",
    noCancellation: "No cancellation request has been submitted.",
    reviewHeading: "Tour review",
    reviewAvailable: "Share a review for this completed tour.",
    reviewRating: "Rating",
    reviewText: "Review text",
    reviewTextHint: "What stood out about this tour?",
    submitReview: "Submit review",
    reviewSubmitted: "Review submitted for this completed tour.",
    reviewExists: "You have already reviewed this completed booking.",
    reviewUnavailable: "Reviews are available after a tour is completed.",
    requestsHeading: "Personalized requests",
    requestsIntro: "See the latest status of your customer-initiated trip requests.",
    noRequests: "You have no personalized requests in this demo account.",
    requestStatus: "Request status",
    revision: "Revision",
    updated: "Updated",
    guideProfileHeading: "Your guide profile",
    guideProfileIntro: "Update only your allowlisted contact and profile details.",
    shortBio: "Short bio",
    guideProfileSaved: "Guide profile saved in this demo session.",
    scheduleHeading: "Your schedule",
    scheduleIntro: "Only tours assigned to this guide are shown.",
    noAssignments: "No tours are assigned to this guide in the demo fixture.",
    assignedToursHeading: "Assigned tour details",
    assignmentStatus: "Assignment status",
    tourLanguage: "Tour language",
    accessibilityNeeds: "Accessibility needs",
    noneRecorded: "None recorded",
    readOnlyAssignment: "Assignment details are read-only. Guides cannot accept, complete, cancel, or administer tours here.",
    usersHeading: "Users and roles",
    usersIntro: "Review active demo identities and their current role.",
    role: "Role",
    active: "Active",
    saveRole: "Save role",
    roleSaved: "Role updated in this demo session.",
    roleError: "We could not update this role.",
    locationsHeading: "Locations",
    locationsIntro: "Published location records available to the admin demo.",
    noLocations: "No locations are available.",
    fixedToursHeading: "Fixed tours and departures",
    fixedToursIntro: "Review fixed-tour versions and their scheduled departures.",
    noTours: "No fixed tours are available.",
    noDepartures: "No departures are available.",
    personalizedHeading: "Personalized requests",
    personalizedIntro: "Review customer-initiated requests and record a demo decision.",
    noPersonalizedRequests: "No personalized requests are waiting for review.",
    decision: "Decision",
    decisionNote: "Decision note",
    changesRequested: "Changes requested",
    approved: "Approved",
    rejected: "Rejected",
    saveDecision: "Save request decision",
    decisionSaved: "Request decision saved in this demo session.",
    decisionError: "We could not save this request decision.",
    bookingsCancellationsHeading: "Bookings and cancellations",
    bookingsCancellationsIntro: "Review booking status, payment status, and customer cancellation requests.",
    noAdminBookings: "No bookings are available.",
    noCancellationRequests: "No cancellation requests are waiting for review.",
    approveCancellation: "Approve cancellation",
    rejectCancellation: "Reject cancellation",
    cancellationNote: "Administrator note",
    cancellationDecisionSaved: "Cancellation decision saved in this demo session.",
    cancellationDecisionError: "We could not save this cancellation decision.",
    assignmentsHeading: "Fixed-departure guide assignment",
    assignmentsIntro: "Assign guides only to confirmed fixed departures.",
    fixedDeparturesOnly: "Fixed departures only",
    assignGuide: "Assign guide",
    guideAssignmentSaved: "Guide assignment saved in this demo session.",
    guideAssignmentError: "We could not save this guide assignment.",
    noAssignableBookings: "No confirmed fixed departures are available for assignment.",
    personalizedAssignmentGap:
      "Personalized-tour guide assignment is not supported by the current production RPC.",
    reportHeading: "Simulated reporting",
    reportIntro: "These counts are calculated from the local demo fixture.",
    reportGenerated: "Generated",
    usersCount: "Users",
    customersCount: "Customers",
    guidesCount: "Guides",
    adminsCount: "Administrators",
    bookingCount: "Bookings",
    confirmedCount: "Confirmed bookings",
    completedCount: "Completed bookings",
    paidCount: "Paid bookings",
    pendingCancellationCount: "Pending cancellations",
    reportDisclosure: "Demo-only reporting; no live analytics or production persistence is connected.",
    catalogLink: "Open catalog review",
    catalogIntro: "Catalog review remains on its existing admin route.",
    statusLabels: {
      pending_payment: "Pending payment",
      payment_processing: "Payment processing",
      payment_review: "Payment review",
      payment_failed: "Payment failed",
      expired: "Expired",
      confirmed: "Confirmed",
      cancelled: "Cancelled",
      completed: "Completed",
    },
    requestStatusLabels: {
      draft: "Draft",
      pending_review: "Pending review",
      changes_requested: "Changes requested",
      approved: "Approved",
      rejected: "Rejected",
      expired: "Expired",
    },
    cancellationStatusLabels: {
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
    },
    assignmentStatusLabels: {
      assigned: "Assigned",
      accepted: "Accepted",
      completed: "Completed",
      closed: "Closed",
    },
  },
  vi: {
    brand: "LocalLens",
    eyebrow: "Không gian LocalLens của bạn",
    overview: "Tổng quan",
    demoOnly: "Chỉ là bản demo",
    demoNotice:
      "Cổng này dùng danh tính mẫu và dữ liệu trong phiên trình duyệt. Đây không phải xác thực, bảo mật hay lưu trữ production.",
    loading: "Đang tải cổng…",
    loadingData: "Đang tải dữ liệu cổng…",
    retry: "Thử lại",
    errorTitle: "Không thể tải cổng này",
    errorMessage: "Dữ liệu mẫu có thể không khả dụng hoặc không hợp lệ. Hãy thử tải lại dữ liệu mẫu.",
    chooseIdentity: "Chọn danh tính demo",
    signInHeading: "Đăng nhập tài khoản demo",
    signInIntro: "Chọn một danh tính mẫu để khám phá khu vực khách hàng, hướng dẫn viên hoặc quản trị viên.",
    signInDisclosure:
      "Đăng nhập demo chỉ là lớp trải nghiệm cục bộ. Nó không xác minh tài khoản thật và không bảo vệ dữ liệu production.",
    continueAs: "Tiếp tục với",
    signedInAs: "Đang đăng nhập với",
    customer: "Khách hàng",
    guide: "Hướng dẫn viên",
    admin: "Quản trị viên",
    accountPortal: "Cổng khách hàng",
    guidePortal: "Cổng hướng dẫn viên",
    adminPortal: "Cổng quản trị viên",
    accountNav: "Tài khoản",
    guideNav: "Không gian hướng dẫn",
    adminNav: "Không gian quản trị",
    signOut: "Đăng xuất",
    accessDeniedTitle: "Cổng khách hàng không khả dụng",
    guideAccessDeniedTitle: "Cổng hướng dẫn viên không khả dụng",
    adminAccessDeniedTitle: "Cổng quản trị viên không khả dụng",
    accessDeniedMessage: "Trang này chỉ dành cho vai trò đang đăng nhập.",
    signedInAsRole: "Bạn đang đăng nhập với vai trò",
    openYourPortal: "Mở cổng của bạn",
    customerHeading: "Cổng khách hàng của bạn",
    customerIntro: "Quản lý thông tin, booking và yêu cầu của bạn tại một nơi.",
    profileHeading: "Hồ sơ của bạn",
    profileIntro: "Trong demo này chỉ các trường dưới đây được phép chỉnh sửa.",
    fullName: "Họ và tên",
    nationality: "Quốc tịch",
    email: "Email",
    phone: "Điện thoại",
    language: "Ngôn ngữ",
    english: "Tiếng Anh",
    vietnamese: "Tiếng Việt",
    saveProfile: "Lưu hồ sơ",
    saving: "Đang lưu…",
    profileSaved: "Đã lưu hồ sơ trong phiên demo này.",
    profileError: "Không thể lưu hồ sơ.",
    bookingsHeading: "Booking của bạn",
    bookingsIntro: "Theo dõi trạng thái booking và thanh toán riêng biệt.",
    noBookings: "Tài khoản demo này chưa có booking.",
    bookingStatus: "Trạng thái booking",
    paymentStatus: "Trạng thái thanh toán",
    partySize: "Số khách",
    meetingPoint: "Điểm hẹn",
    date: "Ngày",
    created: "Ngày tạo",
    paid: "Đã thanh toán",
    paymentPending: "Đang chờ thanh toán",
    paymentNotAvailable: "Chưa có trạng thái thanh toán",
    total: "Tổng cộng",
    simulatedPayment: "Thanh toán chỉ mô phỏng trong demo luận văn; không thu thập thông tin thẻ hay phát sinh giao dịch thật.",
    cancellationHeading: "Yêu cầu hủy",
    requestCancellation: "Yêu cầu hủy booking",
    cancellationReason: "Lý do hủy",
    cancellationReasonHint: "Cho quản trị viên biết lý do bạn cần hủy.",
    sendCancellation: "Gửi yêu cầu hủy",
    cancelForm: "Đóng biểu mẫu",
    cancellationPending: "Yêu cầu hủy đang chờ quản trị viên quyết định.",
    cancellationApproved: "Quản trị viên đã duyệt yêu cầu hủy.",
    cancellationRejected: "Quản trị viên đã từ chối yêu cầu hủy.",
    cancellationSent: "Đã gửi yêu cầu hủy.",
    cancellationError: "Không thể gửi yêu cầu hủy.",
    noCancellation: "Chưa có yêu cầu hủy nào.",
    reviewHeading: "Đánh giá tour",
    reviewAvailable: "Chia sẻ đánh giá cho tour đã hoàn thành.",
    reviewRating: "Điểm đánh giá",
    reviewText: "Nội dung đánh giá",
    reviewTextHint: "Điều gì đáng nhớ trong tour này?",
    submitReview: "Gửi đánh giá",
    reviewSubmitted: "Đã gửi đánh giá cho tour đã hoàn thành.",
    reviewExists: "Bạn đã đánh giá booking đã hoàn thành này.",
    reviewUnavailable: "Bạn có thể đánh giá sau khi tour hoàn thành.",
    requestsHeading: "Yêu cầu cá nhân hóa",
    requestsIntro: "Xem trạng thái mới nhất của yêu cầu chuyến đi do bạn tạo.",
    noRequests: "Tài khoản demo này chưa có yêu cầu cá nhân hóa.",
    requestStatus: "Trạng thái yêu cầu",
    revision: "Bản sửa",
    updated: "Cập nhật",
    guideProfileHeading: "Hồ sơ hướng dẫn viên",
    guideProfileIntro: "Chỉ cập nhật thông tin liên hệ và hồ sơ được cho phép.",
    shortBio: "Giới thiệu ngắn",
    guideProfileSaved: "Đã lưu hồ sơ hướng dẫn viên trong phiên demo này.",
    scheduleHeading: "Lịch của bạn",
    scheduleIntro: "Chỉ các tour được phân công cho hướng dẫn viên này được hiển thị.",
    noAssignments: "Hướng dẫn viên này chưa có tour trong dữ liệu mẫu.",
    assignedToursHeading: "Chi tiết tour được phân công",
    assignmentStatus: "Trạng thái phân công",
    tourLanguage: "Ngôn ngữ tour",
    accessibilityNeeds: "Nhu cầu tiếp cận",
    noneRecorded: "Không có",
    readOnlyAssignment: "Chi tiết phân công chỉ đọc. Hướng dẫn viên không thể nhận, hoàn thành, hủy hoặc quản trị tour tại đây.",
    usersHeading: "Người dùng và vai trò",
    usersIntro: "Xem danh tính demo đang hoạt động và vai trò hiện tại.",
    role: "Vai trò",
    active: "Hoạt động",
    saveRole: "Lưu vai trò",
    roleSaved: "Đã cập nhật vai trò trong phiên demo này.",
    roleError: "Không thể cập nhật vai trò.",
    locationsHeading: "Địa điểm",
    locationsIntro: "Các bản ghi địa điểm đã xuất bản trong admin demo.",
    noLocations: "Chưa có địa điểm.",
    fixedToursHeading: "Tour cố định và lịch khởi hành",
    fixedToursIntro: "Xem phiên bản tour cố định và các lịch khởi hành.",
    noTours: "Chưa có tour cố định.",
    noDepartures: "Chưa có lịch khởi hành.",
    personalizedHeading: "Yêu cầu cá nhân hóa",
    personalizedIntro: "Xem yêu cầu do khách hàng tạo và ghi nhận quyết định demo.",
    noPersonalizedRequests: "Không có yêu cầu cá nhân hóa chờ duyệt.",
    decision: "Quyết định",
    decisionNote: "Ghi chú quyết định",
    changesRequested: "Yêu cầu chỉnh sửa",
    approved: "Đã duyệt",
    rejected: "Từ chối",
    saveDecision: "Lưu quyết định yêu cầu",
    decisionSaved: "Đã lưu quyết định yêu cầu trong phiên demo này.",
    decisionError: "Không thể lưu quyết định yêu cầu.",
    bookingsCancellationsHeading: "Booking và yêu cầu hủy",
    bookingsCancellationsIntro: "Xem trạng thái booking, thanh toán và yêu cầu hủy của khách.",
    noAdminBookings: "Chưa có booking.",
    noCancellationRequests: "Không có yêu cầu hủy chờ duyệt.",
    approveCancellation: "Duyệt yêu cầu hủy",
    rejectCancellation: "Từ chối yêu cầu hủy",
    cancellationNote: "Ghi chú quản trị viên",
    cancellationDecisionSaved: "Đã lưu quyết định hủy trong phiên demo này.",
    cancellationDecisionError: "Không thể lưu quyết định hủy.",
    assignmentsHeading: "Phân công hướng dẫn viên cho lịch cố định",
    assignmentsIntro: "Chỉ phân công cho booking lịch cố định đã xác nhận.",
    fixedDeparturesOnly: "Chỉ lịch khởi hành cố định",
    assignGuide: "Phân công hướng dẫn viên",
    guideAssignmentSaved: "Đã lưu phân công trong phiên demo này.",
    guideAssignmentError: "Không thể lưu phân công.",
    noAssignableBookings: "Không có lịch cố định đã xác nhận để phân công.",
    personalizedAssignmentGap: "RPC production hiện tại không hỗ trợ phân công hướng dẫn viên cho tour cá nhân hóa.",
    reportHeading: "Báo cáo mô phỏng",
    reportIntro: "Các số liệu được tính từ dữ liệu mẫu cục bộ.",
    reportGenerated: "Tạo lúc",
    usersCount: "Người dùng",
    customersCount: "Khách hàng",
    guidesCount: "Hướng dẫn viên",
    adminsCount: "Quản trị viên",
    bookingCount: "Booking",
    confirmedCount: "Booking đã xác nhận",
    completedCount: "Booking đã hoàn thành",
    paidCount: "Booking đã thanh toán",
    pendingCancellationCount: "Yêu cầu hủy chờ xử lý",
    reportDisclosure: "Báo cáo chỉ dành cho demo; không kết nối phân tích trực tiếp hay lưu trữ production.",
    catalogLink: "Mở duyệt danh mục",
    catalogIntro: "Duyệt danh mục vẫn dùng route admin hiện có.",
    statusLabels: {
      pending_payment: "Chờ thanh toán",
      payment_processing: "Đang xử lý thanh toán",
      payment_review: "Đang rà soát thanh toán",
      payment_failed: "Thanh toán thất bại",
      expired: "Hết hạn",
      confirmed: "Đã xác nhận",
      cancelled: "Đã hủy",
      completed: "Đã hoàn thành",
    },
    requestStatusLabels: {
      draft: "Bản nháp",
      pending_review: "Chờ duyệt",
      changes_requested: "Yêu cầu chỉnh sửa",
      approved: "Đã duyệt",
      rejected: "Từ chối",
      expired: "Hết hạn",
    },
    cancellationStatusLabels: {
      pending: "Chờ xử lý",
      approved: "Đã duyệt",
      rejected: "Từ chối",
    },
    assignmentStatusLabels: {
      assigned: "Đã phân công",
      accepted: "Đã nhận",
      completed: "Đã hoàn thành",
      closed: "Đã đóng",
    },
  },
} as const satisfies Record<Locale, Record<string, unknown>>;

export type PortalCopy = typeof PORTAL_COPY[Locale];

export function portalCopy(locale: Locale): PortalCopy {
  return PORTAL_COPY[locale];
}

export function roleLabel(locale: Locale, role: "customer" | "guide" | "admin"): string {
  const copy = portalCopy(locale);
  return copy[role];
}

export function portalPath(locale: Locale, role: "customer" | "guide" | "admin"): string {
  const segment = role === "customer" ? "account" : role;
  return `/${locale}/${segment}/`;
}
