import type { Locale } from "@/lib/i18n/config";

export const PORTAL_COPY = {
  en: {
    brand: "LocalLens",
    eyebrow: "Your LocalLens space",
    overview: "Overview",
    demoOnly: "Demo-only",
    demoNotice:
      "This portal uses seeded demo identities and browser session data. It is not production authentication, security, or persistence.",
    loading: "Loading your portal…",
    loadingData: "Loading portal data…",
    retry: "Try again",
    resetDemo: "Reset LocalLens demo",
    resettingDemo: "Resetting demo…",
    resetComplete: "LocalLens demo state was reset. Choose an identity to continue.",
    resetError: "The LocalLens demo could not be fully reset. Try again.",
    errorTitle: "We could not load this portal",
    errorMessage: "The demo fixture may be unavailable or invalid. Try again to reload the seeded data.",
    serviceUnavailableTitle: "Service unavailable",
    serviceUnavailableMessage: "LocalLens sign-in is temporarily unavailable. Try again or contact support with the reference below.",
    correlationIdLabel: "Reference ID",
    chooseIdentity: "Choose a demo identity",
    signInHeading: "Sign in to your demo account",
    signInIntro:
      "Select a seeded identity to explore the customer, guide, or administrator experience.",
    signInDisclosure:
      "Demo sign-in is a local UX boundary only. It does not verify a real account or protect production data.",
    runtimeSignInEyebrow: "Secure account access",
    runtimeSignInHeading: "Sign in to LocalLens",
    runtimeSignInIntro: "Use the email and password for your LocalLens account.",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in…",
    runtimeAuthError: "We could not sign you in. Check your details and try again.",
    runtimeActionError: "We could not complete that account action. Try again.",
    runtimeConnected: "Secure runtime",
    runtimeShellHeading: "Your secure portal",
    runtimeAccessDeniedTitle: "Access denied",
    runtimeDisclosure: "Secure runtime connected. Customer bookings, cancellation history, and fixed-departure guide assignments use authoritative local runtime data.",
    displayName: "Display name",
    continueAs: "Continue as",
    signedInAs: "Signed in as",
    customer: "Customer",
    guide: "Guide",
    admin: "Administrator",
    accountPortal: "Customer portal",
    guidePortal: "Guide portal",
    adminPortal: "Admin portal",
    accountNav: "Account",
    guideNav: "Guide space",
    adminNav: "Admin space",
    signOut: "Sign out",
    accessDeniedTitle: "Customer portal unavailable",
    guideAccessDeniedTitle: "Guide portal unavailable",
    adminAccessDeniedTitle: "Admin portal unavailable",
    accessDeniedMessage: "This route is limited to the signed-in role.",
    signedInAsRole: "You are signed in as a",
    openYourPortal: "Open your portal",
    customerHeading: "Your customer portal",
    customerIntro: "Keep your details, bookings, and requests together in one place.",
    profileHeading: "Your profile",
    profileIntro: "Only the fields below are editable in this demo.",
    fullName: "Full name",
    nationality: "Nationality",
    email: "Email",
    phone: "Phone",
    language: "Language",
    english: "English",
    vietnamese: "Vietnamese",
    saveProfile: "Save profile",
    saving: "Saving…",
    profileSaved: "Profile saved in this demo session.",
    profileError: "We could not save your profile.",
    bookingsHeading: "Your bookings",
    bookingsIntro: "Track booking and payment states separately.",
    noBookings: "You have no bookings in this demo account.",
    bookingStatus: "Booking status",
    paymentStatus: "Payment status",
    partySize: "Party size",
    meetingPoint: "Meeting point",
    date: "Date",
    created: "Created",
    paid: "Paid",
    paymentPending: "Payment pending",
    paymentNotAvailable: "Payment state unavailable",
    total: "Total",
    simulatedPayment: "Payment is simulated for this thesis demo; no card details or real charge are collected.",
    cancellationHeading: "Cancellation",
    cancellationReason: "Cancellation reason",
    reviewHeading: "Tour review",
    reviewAvailable: "Share a review for this completed tour.",
    reviewRating: "Rating",
    reviewText: "Review text",
    reviewTextHint: "What stood out about this tour?",
    submitReview: "Submit review",
    reviewSubmitted: "Review submitted for this completed tour.",
    reviewExists: "You have already reviewed this completed booking.",
    reviewUnavailable: "Reviews are available after a tour is completed.",
    requestsHeading: "Personalized requests",
    requestsIntro: "See the latest status of your customer-initiated trip requests.",
    noRequests: "You have no personalized requests in this demo account.",
    requestStatus: "Request status",
    revision: "Revision",
    updated: "Updated",
    guideProfileHeading: "Your guide profile",
    guideProfileIntro: "Update only your allowlisted contact and profile details.",
    shortBio: "Short bio",
    guideProfileSaved: "Guide profile saved in this demo session.",
    scheduleHeading: "Your schedule",
    scheduleIntro: "Only tours assigned to this guide are shown.",
    noAssignments: "No tours are assigned to this guide in the demo fixture.",
    assignedToursHeading: "Assigned tour details",
    assignmentStatus: "Assignment status",
    estimatedDuration: "Estimated duration",
    durationUnavailable: "Not specified",
    scheduleUnavailable: "Not specified",
    tourLanguage: "Tour language",
    accessibilityNeeds: "Accessibility needs",
    noneRecorded: "None recorded",
    cancellationNotice: "Cancellation status",
    readOnlyAssignment: "Assignment details are read-only. Guides cannot accept, complete, cancel, or administer tours here.",
    usersHeading: "Users and roles",
    usersIntro: "Review active demo identities and their current role.",
    role: "Role",
    active: "Active",
    saveRole: "Save role",
    roleSaved: "Role updated in this demo session.",
    roleError: "We could not update this role.",
    locationsHeading: "Locations",
    locationsIntro: "Published location records available to the admin demo.",
    noLocations: "No locations are available.",
    fixedToursHeading: "Fixed tours and departures",
    fixedToursIntro: "Review fixed-tour versions and their scheduled departures.",
    noTours: "No fixed tours are available.",
    noDepartures: "No departures are available.",
    personalizedHeading: "Personalized requests",
    personalizedIntro: "Review customer-initiated requests and record a demo decision.",
    noPersonalizedRequests: "No personalized requests are waiting for review.",
    decision: "Decision",
    decisionNote: "Decision note",
    changesRequested: "Changes requested",
    approved: "Approved",
    rejected: "Rejected",
    saveDecision: "Save request decision",
    decisionSaved: "Request decision saved in this demo session.",
    decisionError: "We could not save this request decision.",
    quoteAmount: "Demo quote amount (VND)",
    quoteFixtureSource: "The remaining quote facts come from the seeded demo quote fixture and are issued only by this admin action.",
    issueQuote: "Issue demo quote",
    quoteIssued: "Demo quote issued in this session.",
    quoteError: "We could not issue this demo quote.",
    bookingsCancellationsHeading: "Booking management",
    bookingsCancellationsIntro: "Review booking status, payment status, and immutable cancellation history.",
    cancelledAt: "Cancelled at",
    otherReason: "Other reason",
    noAdminBookings: "No bookings are available.",
    assignmentsHeading: "Fixed-departure guide assignment",
    assignmentsIntro: "Assign guides only to confirmed fixed departures.",
    fixedDeparturesOnly: "Fixed departures only",
    assignGuide: "Assign guide",
    guideAssignmentSaved: "Guide assignment saved in this demo session.",
    guideAssignmentError: "We could not save this guide assignment.",
    noAssignableBookings: "No confirmed fixed departures are available for assignment.",
    personalizedAssignmentGap:
      "Personalized-tour guide assignment is not supported by the current production RPC.",
    reportHeading: "Simulated reporting",
    reportIntro: "These counts are calculated from the local demo fixture.",
    reportGenerated: "Generated",
    usersCount: "Users",
    customersCount: "Customers",
    guidesCount: "Guides",
    adminsCount: "Administrators",
    bookingCount: "Bookings",
    confirmedCount: "Confirmed bookings",
    completedCount: "Completed bookings",
    paidCount: "Paid bookings",
    reportDisclosure: "Demo-only reporting; no live analytics or production persistence is connected.",
    catalogLink: "Open catalog review",
    catalogIntro: "Catalog review remains on its existing admin route.",
    statusLabels: {
      pending_payment: "Awaiting confirmation",
      payment_processing: "Payment processing",
      payment_review: "Payment review",
      payment_failed: "Payment failed",
      expired: "Expired",
      confirmed: "Confirmed",
      cancelled: "Cancelled",
      completed: "Completed",
    },
    placeStatusLabels: {
      draft: "Draft",
      published: "Published",
      archived: "Archived",
    },
    tourStatusLabels: {
      draft: "Draft",
      published: "Published",
      archived: "Archived",
    },
    departureStatusLabels: {
      scheduled: "Scheduled",
      sold_out: "Sold out",
      cancelled: "Cancelled",
      completed: "Completed",
    },
    paymentStatusLabels: {
      pending: "Pending payment",
      paid: "Paid",
      failed: "Payment failed",
      review: "Payment review",
    },
    requestStatusLabels: {
      draft: "Draft",
      pending_review: "Pending review",
      changes_requested: "Changes requested",
      approved: "Approved",
      rejected: "Rejected",
      expired: "Expired",
    },
    assignmentStatusLabels: {
      assigned: "Assigned",
      accepted: "Accepted",
      completed: "Completed",
      closed: "Closed",
    },
  },
  vi: {
    brand: "LocalLens",
    eyebrow: "Không gian LocalLens của bạn",
    overview: "Tổng quan",
    demoOnly: "Chỉ là bản demo",
    demoNotice:
      "Cổng này dùng danh tính mẫu và dữ liệu trong phiên trình duyệt. Đây không phải xác thực, bảo mật hay lưu trữ production.",
    loading: "Đang tải cổng…",
    loadingData: "Đang tải dữ liệu cổng…",
    retry: "Thử lại",
    resetDemo: "Đặt lại demo LocalLens",
    resettingDemo: "Đang đặt lại demo…",
    resetComplete: "Đã đặt lại trạng thái demo LocalLens. Hãy chọn một danh tính để tiếp tục.",
    resetError: "Không thể đặt lại đầy đủ demo LocalLens. Hãy thử lại.",
    errorTitle: "Không thể tải cổng này",
    errorMessage: "Dữ liệu mẫu có thể không khả dụng hoặc không hợp lệ. Hãy thử tải lại dữ liệu mẫu.",
    serviceUnavailableTitle: "Dịch vụ không khả dụng",
    serviceUnavailableMessage: "Đăng nhập LocalLens hiện tạm thời không khả dụng. Hãy thử lại hoặc liên hệ hỗ trợ với mã tham chiếu bên dưới.",
    correlationIdLabel: "Mã tham chiếu",
    chooseIdentity: "Chọn danh tính demo",
    signInHeading: "Đăng nhập tài khoản demo",
    signInIntro: "Chọn một danh tính mẫu để khám phá khu vực khách hàng, hướng dẫn viên hoặc quản trị viên.",
    signInDisclosure:
      "Đăng nhập demo chỉ là lớp trải nghiệm cục bộ. Nó không xác minh tài khoản thật và không bảo vệ dữ liệu production.",
    runtimeSignInEyebrow: "Truy cập tài khoản bảo mật",
    runtimeSignInHeading: "Đăng nhập LocalLens",
    runtimeSignInIntro: "Sử dụng email và mật khẩu của tài khoản LocalLens.",
    password: "Mật khẩu",
    signIn: "Đăng nhập",
    signingIn: "Đang đăng nhập…",
    runtimeAuthError: "Không thể đăng nhập. Hãy kiểm tra thông tin và thử lại.",
    runtimeActionError: "Không thể hoàn tất thao tác tài khoản. Hãy thử lại.",
    runtimeConnected: "Runtime bảo mật",
    runtimeShellHeading: "Cổng bảo mật của bạn",
    runtimeAccessDeniedTitle: "Truy cập bị từ chối",
    runtimeDisclosure: "Runtime bảo mật đã kết nối. Booking khách hàng, lịch sử hủy và phân công hướng dẫn viên cho tour cố định dùng dữ liệu runtime cục bộ chính thức.",
    displayName: "Tên hiển thị",
    continueAs: "Tiếp tục với",
    signedInAs: "Đang đăng nhập với",
    customer: "Khách hàng",
    guide: "Hướng dẫn viên",
    admin: "Quản trị viên",
    accountPortal: "Cổng khách hàng",
    guidePortal: "Cổng hướng dẫn viên",
    adminPortal: "Cổng quản trị viên",
    accountNav: "Tài khoản",
    guideNav: "Không gian hướng dẫn",
    adminNav: "Không gian quản trị",
    signOut: "Đăng xuất",
    accessDeniedTitle: "Cổng khách hàng không khả dụng",
    guideAccessDeniedTitle: "Cổng hướng dẫn viên không khả dụng",
    adminAccessDeniedTitle: "Cổng quản trị viên không khả dụng",
    accessDeniedMessage: "Trang này chỉ dành cho vai trò đang đăng nhập.",
    signedInAsRole: "Bạn đang đăng nhập với vai trò",
    openYourPortal: "Mở cổng của bạn",
    customerHeading: "Cổng khách hàng của bạn",
    customerIntro: "Quản lý thông tin, booking và yêu cầu của bạn tại một nơi.",
    profileHeading: "Hồ sơ của bạn",
    profileIntro: "Trong demo này chỉ các trường dưới đây được phép chỉnh sửa.",
    fullName: "Họ và tên",
    nationality: "Quốc tịch",
    email: "Email",
    phone: "Điện thoại",
    language: "Ngôn ngữ",
    english: "Tiếng Anh",
    vietnamese: "Tiếng Việt",
    saveProfile: "Lưu hồ sơ",
    saving: "Đang lưu…",
    profileSaved: "Đã lưu hồ sơ trong phiên demo này.",
    profileError: "Không thể lưu hồ sơ.",
    bookingsHeading: "Booking của bạn",
    bookingsIntro: "Theo dõi trạng thái booking và thanh toán riêng biệt.",
    noBookings: "Tài khoản demo này chưa có booking.",
    bookingStatus: "Trạng thái booking",
    paymentStatus: "Trạng thái thanh toán",
    partySize: "Số khách",
    meetingPoint: "Điểm hẹn",
    date: "Ngày",
    created: "Ngày tạo",
    paid: "Đã thanh toán",
    paymentPending: "Đang chờ thanh toán",
    paymentNotAvailable: "Chưa có trạng thái thanh toán",
    total: "Tổng cộng",
    simulatedPayment: "Thanh toán chỉ mô phỏng trong demo luận văn; không thu thập thông tin thẻ hay phát sinh giao dịch thật.",
    cancellationHeading: "Hủy booking",
    cancellationReason: "Lý do hủy",
    reviewHeading: "Đánh giá tour",
    reviewAvailable: "Chia sẻ đánh giá cho tour đã hoàn thành.",
    reviewRating: "Điểm đánh giá",
    reviewText: "Nội dung đánh giá",
    reviewTextHint: "Điều gì đáng nhớ trong tour này?",
    submitReview: "Gửi đánh giá",
    reviewSubmitted: "Đã gửi đánh giá cho tour đã hoàn thành.",
    reviewExists: "Bạn đã đánh giá booking đã hoàn thành này.",
    reviewUnavailable: "Bạn có thể đánh giá sau khi tour hoàn thành.",
    requestsHeading: "Yêu cầu cá nhân hóa",
    requestsIntro: "Xem trạng thái mới nhất của yêu cầu chuyến đi do bạn tạo.",
    noRequests: "Tài khoản demo này chưa có yêu cầu cá nhân hóa.",
    requestStatus: "Trạng thái yêu cầu",
    revision: "Bản sửa",
    updated: "Cập nhật",
    guideProfileHeading: "Hồ sơ hướng dẫn viên",
    guideProfileIntro: "Chỉ cập nhật thông tin liên hệ và hồ sơ được cho phép.",
    shortBio: "Giới thiệu ngắn",
    guideProfileSaved: "Đã lưu hồ sơ hướng dẫn viên trong phiên demo này.",
    scheduleHeading: "Lịch của bạn",
    scheduleIntro: "Chỉ các tour được phân công cho hướng dẫn viên này được hiển thị.",
    noAssignments: "Hướng dẫn viên này chưa có tour trong dữ liệu mẫu.",
    assignedToursHeading: "Chi tiết tour được phân công",
    assignmentStatus: "Trạng thái phân công",
    estimatedDuration: "Thời lượng dự kiến",
    durationUnavailable: "Chưa xác định",
    scheduleUnavailable: "Chưa xác định",
    tourLanguage: "Ngôn ngữ tour",
    accessibilityNeeds: "Nhu cầu tiếp cận",
    noneRecorded: "Không có",
    cancellationNotice: "Trạng thái hủy",
    readOnlyAssignment: "Chi tiết phân công chỉ đọc. Hướng dẫn viên không thể nhận, hoàn thành, hủy hoặc quản trị tour tại đây.",
    usersHeading: "Người dùng và vai trò",
    usersIntro: "Xem danh tính demo đang hoạt động và vai trò hiện tại.",
    role: "Vai trò",
    active: "Hoạt động",
    saveRole: "Lưu vai trò",
    roleSaved: "Đã cập nhật vai trò trong phiên demo này.",
    roleError: "Không thể cập nhật vai trò.",
    locationsHeading: "Địa điểm",
    locationsIntro: "Các bản ghi địa điểm đã xuất bản trong admin demo.",
    noLocations: "Chưa có địa điểm.",
    fixedToursHeading: "Tour cố định và lịch khởi hành",
    fixedToursIntro: "Xem phiên bản tour cố định và các lịch khởi hành.",
    noTours: "Chưa có tour cố định.",
    noDepartures: "Chưa có lịch khởi hành.",
    personalizedHeading: "Yêu cầu cá nhân hóa",
    personalizedIntro: "Xem yêu cầu do khách hàng tạo và ghi nhận quyết định demo.",
    noPersonalizedRequests: "Không có yêu cầu cá nhân hóa chờ duyệt.",
    decision: "Quyết định",
    decisionNote: "Ghi chú quyết định",
    changesRequested: "Yêu cầu chỉnh sửa",
    approved: "Đã duyệt",
    rejected: "Từ chối",
    saveDecision: "Lưu quyết định yêu cầu",
    decisionSaved: "Đã lưu quyết định yêu cầu trong phiên demo này.",
    decisionError: "Không thể lưu quyết định yêu cầu.",
    quoteAmount: "Số tiền báo giá demo (VND)",
    quoteFixtureSource: "Các dữ kiện báo giá còn lại lấy từ fixture báo giá demo đã seed và chỉ được phát hành qua thao tác admin này.",
    issueQuote: "Phát hành báo giá demo",
    quoteIssued: "Đã phát hành báo giá demo trong phiên này.",
    quoteError: "Không thể phát hành báo giá demo.",
    bookingsCancellationsHeading: "Quản lý đơn đặt tour",
    bookingsCancellationsIntro: "Xem trạng thái booking, thanh toán và lịch sử hủy bất biến.",
    cancelledAt: "Thời điểm hủy",
    otherReason: "Mô tả lý do khác",
    noAdminBookings: "Chưa có booking.",
    assignmentsHeading: "Phân công hướng dẫn viên cho lịch cố định",
    assignmentsIntro: "Chỉ phân công cho booking lịch cố định đã xác nhận.",
    fixedDeparturesOnly: "Chỉ lịch khởi hành cố định",
    assignGuide: "Phân công hướng dẫn viên",
    guideAssignmentSaved: "Đã lưu phân công trong phiên demo này.",
    guideAssignmentError: "Không thể lưu phân công.",
    noAssignableBookings: "Không có lịch cố định đã xác nhận để phân công.",
    personalizedAssignmentGap: "RPC production hiện tại không hỗ trợ phân công hướng dẫn viên cho tour cá nhân hóa.",
    reportHeading: "Báo cáo mô phỏng",
    reportIntro: "Các số liệu được tính từ dữ liệu mẫu cục bộ.",
    reportGenerated: "Tạo lúc",
    usersCount: "Người dùng",
    customersCount: "Khách hàng",
    guidesCount: "Hướng dẫn viên",
    adminsCount: "Quản trị viên",
    bookingCount: "Booking",
    confirmedCount: "Booking đã xác nhận",
    completedCount: "Booking đã hoàn thành",
    paidCount: "Booking đã thanh toán",
    reportDisclosure: "Báo cáo chỉ dành cho demo; không kết nối phân tích trực tiếp hay lưu trữ production.",
    catalogLink: "Mở duyệt danh mục",
    catalogIntro: "Duyệt danh mục vẫn dùng route admin hiện có.",
    statusLabels: {
      pending_payment: "Chờ xác nhận",
      payment_processing: "Đang xử lý thanh toán",
      payment_review: "Đang rà soát thanh toán",
      payment_failed: "Thanh toán thất bại",
      expired: "Hết hạn",
      confirmed: "Đã xác nhận",
      cancelled: "Đã hủy",
      completed: "Đã hoàn thành",
    },
    placeStatusLabels: {
      draft: "Bản nháp",
      published: "Đã xuất bản",
      archived: "Đã lưu trữ",
    },
    tourStatusLabels: {
      draft: "Bản nháp",
      published: "Đã xuất bản",
      archived: "Đã lưu trữ",
    },
    departureStatusLabels: {
      scheduled: "Đã lên lịch",
      sold_out: "Hết chỗ",
      cancelled: "Đã hủy",
      completed: "Đã hoàn thành",
    },
    paymentStatusLabels: {
      pending: "Chờ thanh toán",
      paid: "Đã thanh toán",
      failed: "Thanh toán thất bại",
      review: "Đang rà soát thanh toán",
    },
    requestStatusLabels: {
      draft: "Bản nháp",
      pending_review: "Chờ duyệt",
      changes_requested: "Yêu cầu chỉnh sửa",
      approved: "Đã duyệt",
      rejected: "Từ chối",
      expired: "Hết hạn",
    },
    assignmentStatusLabels: {
      assigned: "Đã phân công",
      accepted: "Đã nhận",
      completed: "Đã hoàn thành",
      closed: "Đã đóng",
    },
  },
} as const satisfies Record<Locale, Record<string, unknown>>;

export type PortalCopy = typeof PORTAL_COPY[Locale];

export function portalCopy(locale: Locale): PortalCopy {
  return PORTAL_COPY[locale];
}

export function roleLabel(locale: Locale, role: "customer" | "guide" | "admin"): string {
  const copy = portalCopy(locale);
  return copy[role];
}

export function signedInRoleText(locale: Locale, role: "customer" | "guide" | "admin"): string {
  const copy = portalCopy(locale);
  const articleSuffix = locale === "en" && role === "admin" ? "n" : "";
  return `${copy.signedInAsRole}${articleSuffix} ${roleLabel(locale, role)}.`;
}

export function portalPath(locale: Locale, role: "customer" | "guide" | "admin"): string {
  const segment = role === "customer" ? "account" : role;
  return `/${locale}/${segment}/`;
}
