import { bookingStatusLabels } from '@/lib/i18n/booking-status';
import type { Locale } from "@/lib/i18n/config";

export const PORTAL_COPY = {
  en: {
    brand: "LocalLens",
    eyebrow: "Your LocalLens space",
    overview: "Overview",
    demoOnly: "Sample experience",
    demoNotice:
      "This portal uses preloaded sample accounts and browser-session data. Changes remain in this browser and are not saved to the live system.",
    loading: "Loading your portal…",
    loadingData: "Loading portal data…",
    retry: "Try again",
    resetDemo: "Reset LocalLens experience",
    resettingDemo: "Resetting experience…",
    resetComplete: "LocalLens experience was reset. Choose an account to continue.",
    resetError: "The LocalLens experience could not be fully reset. Try again.",
    errorTitle: "We could not load this portal",
    errorMessage: "The sample data may be unavailable or invalid. Try again to reload it.",
    serviceUnavailableTitle: "Service unavailable",
    serviceUnavailableMessage: "LocalLens sign-in is temporarily unavailable. Try again or contact support with the reference below.",
    correlationIdLabel: "Reference ID",
    chooseIdentity: "Choose an account",
    signInHeading: "Choose an account to continue",
    signInIntro:
      "Select a preloaded account to explore the customer, guide, or administrator area.",
    signInDisclosure:
      "This sign-in runs only in this browser. It does not verify a real account or protect live system data.",
    runtimeSignInEyebrow: "Secure account access",
    runtimeSignInHeading: "Sign in to LocalLens",
    runtimeSignInIntro: "Use the email and password for your LocalLens account.",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in…",
    runtimeAuthError: "We could not sign you in. Check your details and try again.",
    runtimeActionError: "We could not complete that account action. Try again.",
    runtimeConnected: "Sample account connected",
    runtimeShellHeading: "Your secure portal",
    runtimeAccessDeniedTitle: "Access denied",
    runtimeDisclosure: "This account uses preloaded sample data for bookings, cancellation history, and guide assignments. Changes stay in this browser session.",
    displayName: "Display name",
    continueAs: "Continue as",
    signedInAs: "Signed in as",
    customer: "Customer",
    guide: "Guide",
    admin: "Administrator",
    accountPortal: "Customer portal",
    guidePortal: "Guide portal",
    adminPortal: "Admin portal",
    accountNav: "Account",
    guideNav: "Guide space",
    adminNav: "Admin space",
    signOut: "Sign out",
    accessDeniedTitle: "Customer portal unavailable",
    guideAccessDeniedTitle: "Guide portal unavailable",
    adminAccessDeniedTitle: "Admin portal unavailable",
    accessDeniedMessage: "This route is limited to the signed-in role.",
    signedInAsRole: "You are signed in as a",
    openYourPortal: "Open your portal",
    customerHeading: "Your customer portal",
    customerIntro: "Keep your details, bookings, and requests together in one place.",
    profileHeading: "Your profile",
    profileIntro: "Only the fields below are editable in this account.",
    fullName: "Full name",
    nationality: "Nationality",
    email: "Email",
    phone: "Phone",
    language: "Language",
    english: "English",
    vietnamese: "Vietnamese",
    saveProfile: "Save profile",
    saving: "Saving…",
    profileSaved: "Profile saved in this browser session only.",
    profileError: "We could not save your profile.",
    bookingsHeading: "Your bookings",
    bookingsIntro: "Track booking and payment states separately.",
    noBookings: "You have no bookings in this account.",
    bookingStatus: "Booking status",
    paymentStatus: "Payment status",
    partySize: "Party size",
    meetingPoint: "Meeting point",
    date: "Date",
    created: "Created",
    paid: "Paid",
    paymentPending: "Payment pending",
    paymentNotAvailable: "Payment state unavailable",
    total: "Total",
    simulatedPayment: "Simulated payment — no card details are entered and no real charge occurs.",
    cancellationHeading: "Cancellation",
    cancellationReason: "Cancellation reason",
    reviewHeading: "Tour review",
    reviewAvailable: "Share a review for this completed tour.",
    reviewRating: "Rating",
    reviewText: "Review text",
    reviewTextHint: "What stood out about this tour?",
    submitReview: "Submit review",
    reviewSubmitted: "Review submitted for this completed tour.",
    reviewExists: "You have already reviewed this completed booking.",
    reviewUnavailable: "Reviews are available after a tour is completed.",
    requestsHeading: "Personalized requests",
    requestsIntro: "See the latest status of your customer-initiated trip requests.",
    noRequests: "You have no personalized requests in this account.",
    requestStatus: "Request status",
    revision: "Revision",
    updated: "Updated",
    guideProfileHeading: "Your guide profile",
    guideProfileIntro: "Update only your allowlisted contact and profile details.",
    shortBio: "Short bio",
    guideProfileSaved: "Guide profile saved in this browser session only.",
    scheduleHeading: "Your schedule",
    scheduleIntro: "Only tours assigned to this guide are shown.",
    noAssignments: "No tours are assigned to this guide in the available sample data.",
    assignedToursHeading: "Assigned tour details",
    assignmentStatus: "Assignment status",
    estimatedDuration: "Estimated duration",
    durationUnavailable: "Not specified",
    scheduleUnavailable: "Not specified",
    tourLanguage: "Tour language",
    accessibilityNeeds: "Accessibility needs",
    noneRecorded: "None recorded",
    cancellationNotice: "Cancellation status",
    readOnlyAssignment: "Assignment details are read-only. Guides cannot accept, complete, cancel, or administer tours here.",
    usersHeading: "Users and roles",
    usersIntro: "Review active sample accounts and their current role.",
    role: "Role",
    active: "Active",
    saveRole: "Save role",
    roleSaved: "Role updated in this browser session only.",
    roleError: "We could not update this role.",
    locationsHeading: "Locations",
    locationsIntro: "Published location records available in this administrator area.",
    noLocations: "No locations are available.",
    fixedToursHeading: "Fixed tours and departures",
    fixedToursIntro: "Review fixed-tour versions and their scheduled departures.",
    noTours: "No fixed tours are available.",
    noDepartures: "No departures are available.",
    personalizedHeading: "Personalized requests",
    personalizedIntro: "Review customer requests and record a decision.",
    noPersonalizedRequests: "No personalized requests are waiting for review.",
    decision: "Decision",
    decisionNote: "Decision note",
    changesRequested: "Changes requested",
    approved: "Approved",
    rejected: "Rejected",
    saveDecision: "Save request decision",
    decisionSaved: "Request decision saved in this browser session only.",
    decisionError: "We could not save this request decision.",
    quoteAmount: "Quote amount (VND)",
    quoteFixtureSource: "Other quote details come from preloaded sample records. A quote is created only when you choose this action.",
    issueQuote: "Create quote",
    quoteIssued: "Quote created in this browser session.",
    quoteError: "We could not create this quote.",
    bookingsCancellationsHeading: "Booking management",
    bookingsCancellationsIntro: "Review booking status, payment status, and immutable cancellation history.",
    cancelledAt: "Cancelled at",
    otherReason: "Other reason",
    noAdminBookings: "No bookings are available.",
    assignmentsHeading: "Fixed-departure guide assignment",
    assignmentsIntro: "Assign guides only to confirmed fixed departures.",
    fixedDeparturesOnly: "Fixed departures only",
    assignGuide: "Assign guide",
    guideAssignmentSaved: "Guide assignment saved in this browser session only.",
    guideAssignmentError: "We could not save this guide assignment.",
    noAssignableBookings: "No confirmed fixed departures are available for assignment.",
    personalizedAssignmentGap:
      "Personalized-tour guide assignment is not supported by the current production RPC.",
    reportHeading: "Simulated reporting",
    reportIntro: "These counts are calculated from sample records available in this browser.",
    reportGenerated: "Generated",
    usersCount: "Users",
    customersCount: "Customers",
    guidesCount: "Guides",
    adminsCount: "Administrators",
    bookingCount: "Bookings",
    confirmedCount: "Confirmed bookings",
    completedCount: "Completed bookings",
    paidCount: "Paid bookings",
    reportDisclosure: "Sample figures only; live analytics and production storage are not connected.",
    catalogLink: "Open catalog review",
    catalogIntro: "Catalog review remains on its existing admin route.",
    statusLabels: bookingStatusLabels.en,
    placeStatusLabels: {
      draft: "Draft",
      published: "Published",
      archived: "Archived",
    },
    tourStatusLabels: {
      draft: "Draft",
      published: "Published",
      archived: "Archived",
    },
    departureStatusLabels: {
      scheduled: "Scheduled",
      sold_out: "Sold out",
      cancelled: "Cancelled",
      completed: "Completed",
    },
    paymentStatusLabels: {
      pending: "Pending payment",
      paid: "Paid",
      failed: "Payment failed",
      review: "Payment review",
    },
    requestStatusLabels: {
      draft: "Draft",
      pending_review: "Pending review",
      changes_requested: "Changes requested",
      approved: "Approved",
      rejected: "Rejected",
      expired: "Expired",
    },
    assignmentStatusLabels: {
      assigned: "Assigned",
      accepted: "Accepted",
      completed: "Completed",
      closed: "Closed",
    },
  },
  vi: {
    brand: "LocalLens",
    eyebrow: "Không gian LocalLens của bạn",
    overview: "Tổng quan",
    demoOnly: "Chế độ trải nghiệm",
    demoNotice:
      "Cổng này dùng tài khoản mẫu và dữ liệu trong phiên trình duyệt. Thay đổi chỉ tồn tại trong trình duyệt, không được lưu vào hệ thống thật.",
    loading: "Đang tải cổng…",
    loadingData: "Đang tải dữ liệu cổng…",
    retry: "Thử lại",
    resetDemo: "Đặt lại trải nghiệm LocalLens",
    resettingDemo: "Đang đặt lại trải nghiệm…",
    resetComplete: "Đã đặt lại trải nghiệm LocalLens. Hãy chọn tài khoản để tiếp tục.",
    resetError: "Không thể đặt lại đầy đủ trải nghiệm LocalLens. Hãy thử lại.",
    errorTitle: "Không thể tải cổng này",
    errorMessage: "Dữ liệu mẫu có thể không khả dụng hoặc không hợp lệ. Hãy thử tải lại dữ liệu mẫu.",
    serviceUnavailableTitle: "Dịch vụ không khả dụng",
    serviceUnavailableMessage: "Đăng nhập LocalLens hiện tạm thời không khả dụng. Hãy thử lại hoặc liên hệ hỗ trợ với mã tham chiếu bên dưới.",
    correlationIdLabel: "Mã tham chiếu",
    chooseIdentity: "Chọn tài khoản",
    signInHeading: "Chọn tài khoản để tiếp tục",
    signInIntro: "Chọn một danh tính mẫu để khám phá khu vực khách hàng, hướng dẫn viên hoặc quản trị viên.",
    signInDisclosure:
      "Đăng nhập này chỉ hoạt động trong trình duyệt. Không xác minh tài khoản thật và không bảo vệ dữ liệu của hệ thống thật.",
    runtimeSignInEyebrow: "Truy cập tài khoản bảo mật",
    runtimeSignInHeading: "Đăng nhập LocalLens",
    runtimeSignInIntro: "Sử dụng email và mật khẩu của tài khoản LocalLens.",
    password: "Mật khẩu",
    signIn: "Đăng nhập",
    signingIn: "Đang đăng nhập…",
    runtimeAuthError: "Không thể đăng nhập. Hãy kiểm tra thông tin và thử lại.",
    runtimeActionError: "Không thể hoàn tất thao tác tài khoản. Hãy thử lại.",
    runtimeConnected: "Đã kết nối tài khoản mẫu",
    runtimeShellHeading: "Cổng bảo mật của bạn",
    runtimeAccessDeniedTitle: "Truy cập bị từ chối",
    runtimeDisclosure: "Tài khoản này dùng dữ liệu mẫu có sẵn cho booking, lịch sử hủy và phân công hướng dẫn viên. Thay đổi chỉ được lưu trong phiên trình duyệt này.",
    displayName: "Tên hiển thị",
    continueAs: "Tiếp tục với",
    signedInAs: "Đang đăng nhập với",
    customer: "Khách hàng",
    guide: "Hướng dẫn viên",
    admin: "Quản trị viên",
    accountPortal: "Cổng khách hàng",
    guidePortal: "Cổng hướng dẫn viên",
    adminPortal: "Cổng quản trị viên",
    accountNav: "Tài khoản",
    guideNav: "Không gian hướng dẫn",
    adminNav: "Không gian quản trị",
    signOut: "Đăng xuất",
    accessDeniedTitle: "Cổng khách hàng không khả dụng",
    guideAccessDeniedTitle: "Cổng hướng dẫn viên không khả dụng",
    adminAccessDeniedTitle: "Cổng quản trị viên không khả dụng",
    accessDeniedMessage: "Trang này chỉ dành cho vai trò đang đăng nhập.",
    signedInAsRole: "Bạn đang đăng nhập với vai trò",
    openYourPortal: "Mở cổng của bạn",
    customerHeading: "Cổng khách hàng của bạn",
    customerIntro: "Quản lý thông tin, booking và yêu cầu của bạn tại một nơi.",
    profileHeading: "Hồ sơ của bạn",
    profileIntro: "Chỉ các trường dưới đây có thể chỉnh sửa trong tài khoản này.",
    fullName: "Họ và tên",
    nationality: "Quốc tịch",
    email: "Email",
    phone: "Điện thoại",
    language: "Ngôn ngữ",
    english: "Tiếng Anh",
    vietnamese: "Tiếng Việt",
    saveProfile: "Lưu hồ sơ",
    saving: "Đang lưu…",
    profileSaved: "Hồ sơ chỉ được lưu trong phiên trình duyệt này.",
    profileError: "Không thể lưu hồ sơ.",
    bookingsHeading: "Booking của bạn",
    bookingsIntro: "Theo dõi trạng thái booking và thanh toán riêng biệt.",
    noBookings: "Tài khoản này chưa có booking.",
    bookingStatus: "Trạng thái đơn",
    paymentStatus: "Trạng thái thanh toán",
    partySize: "Số khách",
    meetingPoint: "Điểm hẹn",
    date: "Ngày",
    created: "Ngày tạo",
    paid: "Đã thanh toán",
    paymentPending: "Đang chờ thanh toán",
    paymentNotAvailable: "Chưa có trạng thái thanh toán",
    total: "Tổng cộng",
    simulatedPayment: "Thanh toán mô phỏng — không nhập thông tin thẻ và không phát sinh giao dịch thật.",
    cancellationHeading: "Hủy booking",
    cancellationReason: "Lý do hủy",
    reviewHeading: "Đánh giá tour",
    reviewAvailable: "Chia sẻ đánh giá cho tour đã hoàn thành.",
    reviewRating: "Điểm đánh giá",
    reviewText: "Nội dung đánh giá",
    reviewTextHint: "Điều gì đáng nhớ trong tour này?",
    submitReview: "Gửi đánh giá",
    reviewSubmitted: "Đã gửi đánh giá cho tour đã hoàn thành.",
    reviewExists: "Bạn đã đánh giá booking đã hoàn thành này.",
    reviewUnavailable: "Bạn có thể đánh giá sau khi tour hoàn thành.",
    requestsHeading: "Yêu cầu cá nhân hóa",
    requestsIntro: "Xem trạng thái mới nhất của yêu cầu chuyến đi do bạn tạo.",
    noRequests: "Tài khoản này chưa có yêu cầu cá nhân hóa.",
    requestStatus: "Trạng thái yêu cầu",
    revision: "Bản sửa",
    updated: "Cập nhật",
    guideProfileHeading: "Hồ sơ hướng dẫn viên",
    guideProfileIntro: "Chỉ cập nhật thông tin liên hệ và hồ sơ được cho phép.",
    shortBio: "Giới thiệu ngắn",
    guideProfileSaved: "Hồ sơ hướng dẫn viên chỉ được lưu trong phiên trình duyệt này.",
    scheduleHeading: "Lịch của bạn",
    scheduleIntro: "Chỉ các tour được phân công cho hướng dẫn viên này được hiển thị.",
    noAssignments: "Hướng dẫn viên này chưa có tour trong dữ liệu mẫu.",
    assignedToursHeading: "Chi tiết tour được phân công",
    assignmentStatus: "Trạng thái phân công",
    estimatedDuration: "Thời lượng dự kiến",
    durationUnavailable: "Chưa xác định",
    scheduleUnavailable: "Chưa xác định",
    tourLanguage: "Ngôn ngữ tour",
    accessibilityNeeds: "Nhu cầu tiếp cận",
    noneRecorded: "Không có",
    cancellationNotice: "Trạng thái hủy",
    readOnlyAssignment: "Chi tiết phân công chỉ đọc. Hướng dẫn viên không thể nhận, hoàn thành, hủy hoặc quản trị tour tại đây.",
    usersHeading: "Người dùng và vai trò",
    usersIntro: "Xem các tài khoản mẫu đang hoạt động và vai trò hiện tại.",
    role: "Vai trò",
    active: "Hoạt động",
    saveRole: "Lưu vai trò",
    roleSaved: "Vai trò chỉ được cập nhật trong phiên trình duyệt này.",
    roleError: "Không thể cập nhật vai trò.",
    locationsHeading: "Địa điểm",
    locationsIntro: "Các bản ghi địa điểm đã xuất bản trong khu vực quản trị này.",
    noLocations: "Chưa có địa điểm.",
    fixedToursHeading: "Tour cố định và lịch khởi hành",
    fixedToursIntro: "Xem phiên bản tour cố định và các lịch khởi hành.",
    noTours: "Chưa có tour cố định.",
    noDepartures: "Chưa có lịch khởi hành.",
    personalizedHeading: "Yêu cầu cá nhân hóa",
    personalizedIntro: "Xem yêu cầu của khách hàng và ghi nhận quyết định.",
    noPersonalizedRequests: "Không có yêu cầu cá nhân hóa chờ duyệt.",
    decision: "Quyết định",
    decisionNote: "Ghi chú quyết định",
    changesRequested: "Yêu cầu chỉnh sửa",
    approved: "Đã duyệt",
    rejected: "Từ chối",
    saveDecision: "Lưu quyết định yêu cầu",
    decisionSaved: "Quyết định chỉ được lưu trong phiên trình duyệt này.",
    decisionError: "Không thể lưu quyết định yêu cầu.",
    quoteAmount: "Số tiền báo giá (VND)",
    quoteFixtureSource: "Thông tin báo giá còn lại lấy từ dữ liệu mẫu có sẵn. Báo giá chỉ được tạo khi bạn chọn thao tác này.",
    issueQuote: "Tạo báo giá",
    quoteIssued: "Báo giá đã được tạo trong phiên trình duyệt này.",
    quoteError: "Không thể tạo báo giá.",
    bookingsCancellationsHeading: "Quản lý đơn đặt tour",
    bookingsCancellationsIntro: "Xem trạng thái booking, thanh toán và lịch sử hủy bất biến.",
    cancelledAt: "Thời điểm hủy",
    otherReason: "Mô tả lý do khác",
    noAdminBookings: "Chưa có booking.",
    assignmentsHeading: "Phân công hướng dẫn viên cho lịch cố định",
    assignmentsIntro: "Chỉ phân công cho booking lịch cố định đã xác nhận.",
    fixedDeparturesOnly: "Chỉ lịch khởi hành cố định",
    assignGuide: "Phân công hướng dẫn viên",
    guideAssignmentSaved: "Phân công chỉ được lưu trong phiên trình duyệt này.",
    guideAssignmentError: "Không thể lưu phân công.",
    noAssignableBookings: "Không có lịch cố định đã xác nhận để phân công.",
    personalizedAssignmentGap: "RPC production hiện tại không hỗ trợ phân công hướng dẫn viên cho tour cá nhân hóa.",
    reportHeading: "Báo cáo mô phỏng",
    reportIntro: "Các số liệu được tính từ dữ liệu mẫu cục bộ.",
    reportGenerated: "Tạo lúc",
    usersCount: "Người dùng",
    customersCount: "Khách hàng",
    guidesCount: "Hướng dẫn viên",
    adminsCount: "Quản trị viên",
    bookingCount: "Booking",
    confirmedCount: "Booking đã xác nhận",
    completedCount: "Booking đã hoàn thành",
    paidCount: "Booking đã thanh toán",
    reportDisclosure: "Số liệu báo cáo là dữ liệu mẫu; chưa kết nối phân tích trực tiếp hay lưu trữ trên hệ thống thật.",
    catalogLink: "Mở duyệt danh mục",
    catalogIntro: "Duyệt danh mục vẫn dùng route admin hiện có.",
    statusLabels: bookingStatusLabels.vi,
    placeStatusLabels: {
      draft: "Bản nháp",
      published: "Đã xuất bản",
      archived: "Đã lưu trữ",
    },
    tourStatusLabels: {
      draft: "Bản nháp",
      published: "Đã xuất bản",
      archived: "Đã lưu trữ",
    },
    departureStatusLabels: {
      scheduled: "Đã lên lịch",
      sold_out: "Hết chỗ",
      cancelled: "Đã hủy",
      completed: "Đã hoàn thành",
    },
    paymentStatusLabels: {
      pending: "Chờ thanh toán",
      paid: "Đã thanh toán",
      failed: "Thanh toán thất bại",
      review: "Đang rà soát thanh toán",
    },
    requestStatusLabels: {
      draft: "Bản nháp",
      pending_review: "Chờ duyệt",
      changes_requested: "Yêu cầu chỉnh sửa",
      approved: "Đã duyệt",
      rejected: "Từ chối",
      expired: "Hết hạn",
    },
    assignmentStatusLabels: {
      assigned: "Đã phân công",
      accepted: "Đã nhận",
      completed: "Đã hoàn thành",
      closed: "Đã đóng",
    },
  },
} as const satisfies Record<Locale, Record<string, unknown>>;

export type PortalCopy = typeof PORTAL_COPY[Locale];

export function portalCopy(locale: Locale): PortalCopy {
  return PORTAL_COPY[locale];
}

export function roleLabel(locale: Locale, role: "customer" | "guide" | "admin"): string {
  const copy = portalCopy(locale);
  return copy[role];
}

export function signedInRoleText(locale: Locale, role: "customer" | "guide" | "admin"): string {
  const copy = portalCopy(locale);
  const articleSuffix = locale === "en" && role === "admin" ? "n" : "";
  return `${copy.signedInAsRole}${articleSuffix} ${roleLabel(locale, role)}.`;
}

export function portalPath(locale: Locale, role: "customer" | "guide" | "admin"): string {
  const segment = role === "customer" ? "account" : role;
  return `/${locale}/${segment}/`;
}
