'use client';
import { bookingPreviewPort } from '@/components/dev/admin-bookings-fixture';
import { emptyBookingFilters,filterBookings,orderLabels,paymentLabels,type BookingFilters,type BookingPreviewPort,type BookingView } from '@/lib/application/admin-bookings-preview';
import { Bell,CheckCircle,ChevronLeft,ChevronRight,Clock,Eye,FileText,Flag,Hourglass,RotateCcw,Search,XCircle } from 'lucide-react';
import { useEffect,useRef,useState } from 'react';
import b from './admin-accounts.module.css';
import s from './admin-bookings-preview.module.css';
const money=(n:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(n);
const date=(v?:string)=>v?new Date(v).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'Chưa phát sinh';
const kind=(v:string)=>v==='fixed'?'Tour cố định':'Tour cá nhân hóa';
function Badge({value,payment=false}:{value:string;payment?:boolean}){return <span className={`${s.badge} ${s[value]}`}>{payment?paymentLabels[value as keyof typeof paymentLabels]:orderLabels[value as keyof typeof orderLabels]}</span>;}
export function AdminBookingsPreview({port=bookingPreviewPort}:{port?:BookingPreviewPort}){
 const [rows,setRows]=useState<BookingView[]>([]),[loading,setLoading]=useState(true),[listError,setListError]=useState(false);
 const [filters,setFilters]=useState<BookingFilters>({...emptyBookingFilters}),[page,setPage]=useState(1),[size,setSize]=useState(6);
 const [selected,setSelected]=useState<BookingView|null>(null),[detailLoading,setDetailLoading]=useState(false),[detailError,setDetailError]=useState(false);
 const [attentionOnly,setAttentionOnly]=useState(false);const request=useRef(0);
 async function load(){setLoading(true);setListError(false);try{setRows(await port.list());}catch{setListError(true);setRows([]);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[port]); // The preview port exposes read operations only.
 async function select(id:string){const version=++request.current;setSelected(null);setDetailLoading(true);setDetailError(false);try{const detail=await port.detail(id);if(version===request.current)setSelected(detail);}catch{if(version===request.current)setDetailError(true);}finally{if(version===request.current)setDetailLoading(false);}}
 function update(key:keyof BookingFilters,value:string){setFilters(v=>({...v,[key]:value}));setPage(1);}
 function reset(){setFilters({...emptyBookingFilters});setAttentionOnly(false);setPage(1);}
 const needsAttention=(r:BookingView)=>r.payment==='review'||r.payment==='failed'||r.status==='pending_payment'||r.status==='expired';
 const invalidRange=!!filters.from&&!!filters.to&&filters.from>filters.to;
 const filtered=invalidRange?[]:filterBookings(rows,filters).filter(r=>!attentionOnly||needsAttention(r));
 const pages=Math.max(1,Math.ceil(filtered.length/size)),current=Math.min(page,pages),visible=filtered.slice((current-1)*size,current*size);
 const attention=rows.filter(needsAttention);
 return <div className={`${b.shell} ${s.shell}`}>
 
 <div className={s.workspace}><div className={s.header}><label><Search size={20}/><input aria-label="Tìm kiếm đơn toàn trang" placeholder="Tìm kiếm mã đơn, khách hàng, tour..." value={filters.query} onChange={e=>update('query',e.target.value)}/></label><button className={s.bell} aria-label="Xem đơn cần chú ý" onClick={()=>{reset();setAttentionOnly(true);}}><Bell/><span>{attention.length}</span></button></div>
 <div className={s.layout}><main><p className={s.crumb}>Trang chủ › Đơn đặt tour</p><h1>Quản lý đơn đặt tour</h1><p className={s.subtitle}>Tra cứu và theo dõi đơn đặt tour, trạng thái thanh toán và lịch sử xử lý của khách hàng.</p>
 <div className={s.metrics}>{[['','Tổng đơn',FileText],['pending_payment','Chờ thanh toán',Hourglass],['confirmed','Đã xác nhận',CheckCircle],['completed','Đã hoàn thành',Flag],['cancelled','Đã hủy',XCircle],['expired','Đã hết hạn',Clock]].map(([status,label,Icon])=>{const I=Icon as typeof FileText;return <button key={String(label)} onClick={()=>{update('status',String(status));setAttentionOnly(false);}}><I/><span>{String(label)}<strong>{loading?'—':rows.filter(r=>!status||r.status===status).length}</strong></span></button>;})}</div>
 <section className={s.card}><div className={s.sectionTitle}><h2><Search size={20}/>Bộ lọc tìm kiếm</h2><button onClick={reset}><RotateCcw size={15}/>Đặt lại</button></div><div className={s.filters}>
 <label>Từ khóa<input placeholder="Mã đơn, tên khách, email, tên tour..." value={filters.query} onChange={e=>update('query',e.target.value)}/></label>
 <label>Loại tour<select value={filters.kind} onChange={e=>update('kind',e.target.value)}><option value="">Tất cả loại tour</option><option value="fixed">Tour cố định</option><option value="personalized">Tour cá nhân hóa</option></select></label>
 <label>Trạng thái đơn<select value={filters.status} onChange={e=>update('status',e.target.value)}><option value="">Tất cả trạng thái</option>{Object.entries(orderLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label>Trạng thái thanh toán<select value={filters.payment} onChange={e=>update('payment',e.target.value)}><option value="">Tất cả thanh toán</option>{Object.entries(paymentLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label>Tạo từ ngày<input type="date" value={filters.from} onChange={e=>update('from',e.target.value)}/></label><label>Đến ngày<input type="date" min={filters.from} value={filters.to} onChange={e=>update('to',e.target.value)}/></label></div>{invalidRange&&<p role="alert" className={s.error}>Ngày kết thúc phải bằng hoặc sau ngày bắt đầu.</p>}{attentionOnly&&<p>Đang xem các đơn cần chú ý. <button onClick={reset}>Xóa bộ lọc</button></p>}</section>
 <section className={s.card}><h2><FileText size={20}/>Danh sách đơn đặt tour <small>({filtered.length} đơn)</small></h2>{loading?<p role="status">Đang tải danh sách đơn…</p>:listError?<div role="alert" className={s.empty}>Không thể tải danh sách đơn đặt tour. Vui lòng thử lại sau<button onClick={()=>void load()}>Thử lại</button></div>:!filtered.length?<div className={s.empty}>Không có đơn đặt tour phù hợp<button onClick={reset}>Xóa bộ lọc</button></div>:<><div className={s.table}><table><thead><tr>{['Mã đơn','Khách đặt','Loại tour','Lịch trình / Lịch khởi hành','Số khách','Tổng tiền','Trạng thái đơn','Thanh toán','Thời gian tạo','Thao tác'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.id} className={selected?.id===r.id?s.selected:''}><td><button className={s.textButton} onClick={()=>void select(r.id)}>{r.id}</button></td><td>{r.customer}</td><td>{kind(r.kind)}</td><td className={s.tour}>{r.tour}<small>{date(r.departure)}</small></td><td>{r.people}</td><td className={s.money}>{money(r.total)}</td><td><Badge value={r.status}/></td><td><Badge value={r.payment} payment/></td><td>{date(r.createdAt)}</td><td><button aria-label={`Xem chi tiết ${r.id}`} onClick={()=>void select(r.id)}><Eye size={14}/>Xem chi tiết</button></td></tr>)}</tbody></table></div><div className={s.pagination}><span>Hiển thị {(current-1)*size+1}–{Math.min(current*size,filtered.length)} trong tổng số {filtered.length} đơn</span><button aria-label="Trang trước" disabled={current===1} onClick={()=>setPage(current-1)}><ChevronLeft size={17}/></button><strong>{current} / {pages}</strong><button aria-label="Trang sau" disabled={current===pages} onClick={()=>setPage(current+1)}><ChevronRight size={17}/></button><label>Số dòng/trang <select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1);}}>{[6,10,20].map(v=><option key={v}>{v}</option>)}</select></label></div></> }</section>
 <section className={s.details} aria-label="Chi tiết đơn đang chọn">{detailLoading?<div className={s.card} role="status">Đang tải chi tiết đơn…</div>:detailError?<div className={s.card} role="alert">Không thể tải thông tin đơn đặt tour. Vui lòng thử lại sau</div>:selected?<><div className={s.card}><h2><FileText size={20}/>Chi tiết đơn đang chọn <small>{selected.id}</small></h2><div className={s.facts}><dl>{[['Mã đơn',selected.id],['Khách đặt',selected.customer],['Email',selected.email],['Loại tour',kind(selected.kind)],['Lịch trình',selected.tour],['Khởi hành',date(selected.departure)],['Số khách',`${selected.people} khách`],['Tổng tiền',money(selected.total)]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}<div><dt>Trạng thái đơn</dt><dd><Badge value={selected.status}/></dd></div><div><dt>Thanh toán</dt><dd><Badge value={selected.payment} payment/></dd></div></dl><div className={s.times}><h3><Clock size={17}/>Các mốc thời gian</h3>{[['Tạo đơn',selected.createdAt],['Hạn giữ chỗ',selected.holdUntil],['Thanh toán',selected.paidAt],['Xác nhận',selected.confirmedAt],['Hoàn thành',selected.completedAt]].map(([k,v])=><p key={k}><span>{k}</span><strong>{date(v)}</strong></p>)}</div></div>{selected.transaction&&<p className={s.transaction}>Mã giao dịch minh họa: <strong>{selected.transaction}</strong></p>}{selected.payment==='review'&&<p className={s.reviewNotice}>Giao dịch đang được rà soát. Trạng thái sẽ được cập nhật bởi luồng thanh toán hoặc nghiệp vụ đối soát; màn hình này chỉ cho phép theo dõi.</p>}</div><div className={s.card}><h2><Clock size={20}/>Lịch sử xử lý</h2><ol className={s.timeline}>{selected.history.map((h,i)=><li key={i}><time>{date(h.at)}</time><div><strong>{h.title}</strong><p>{h.description}</p></div></li>)}</ol><p className={s.muted}>Chỉ hiển thị các sự kiện đã phát sinh trong đơn minh họa.</p></div></>:<div className={`${s.card} ${s.empty}`}><Eye/>Chọn “Xem chi tiết” để theo dõi thông tin và lịch sử xử lý của đơn.</div>}</section>
 </main><aside className={`${s.card} ${s.attention}`}><div className={s.sectionTitle}><h2><Bell color="#efa400" size={22}/>Đơn cần chú ý</h2><button onClick={()=>{reset();setAttentionOnly(true);}}>Xem tất cả</button></div>{attention.slice(0,4).map(r=><button className={s.attentionRow} key={r.id} onClick={()=>void select(r.id)}><span className={s.attentionIcon}><Clock size={22}/></span><span><strong>{r.id}</strong><Badge value={r.payment==='review'||r.payment==='failed'?r.payment:r.status} payment={r.payment==='review'||r.payment==='failed'}/><span>{r.customer}</span><small>{r.tour}</small><strong>{money(r.total)}</strong></span></button>)}{!attention.length&&!loading&&<p>Không có đơn cần chú ý.</p>}</aside></div></div></div>;
}
