'use client';
import { RuntimeGuideAssignmentError,type AdminGuideAssignmentQueueItem,type EligibleGuideCandidate,type RuntimeGuideAssignmentPort } from '@/lib/application/guide-assignment/contracts';
import { Search,Users } from 'lucide-react';
import { useCallback,useEffect,useRef,useState } from 'react';
import s from './admin-assignments.module.css';
import base from './admin-quotes.module.css';
const date=(v:string)=>new Date(v).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
const day=(v:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v));
const language=(v:string)=>v==='vi'?'Tiếng Việt':'Tiếng Anh';
export function AdminAssignments({port}:{port:RuntimeGuideAssignmentPort}){
 const [rows,setRows]=useState<AdminGuideAssignmentQueueItem[]>([]),[guides,setGuides]=useState<EligibleGuideCandidate[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[guideError,setGuideError]=useState('');
 const [selected,setSelected]=useState<AdminGuideAssignmentQueueItem|null>(null),[guide,setGuide]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[kind,setKind]=useState(''),[lang,setLang]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [detail,setDetail]=useState<Awaited<ReturnType<NonNullable<RuntimeGuideAssignmentPort['getAdminAssignmentDetail']>>>|null>(null),[detailError,setDetailError]=useState('');
 useEffect(()=>{let live=true;setDetail(null);setDetailError(selected&&!port.getAdminAssignmentDetail?'Nguồn dữ liệu hiện tại chưa cung cấp lịch sử phân công.':'');if(selected&&port.getAdminAssignmentDetail)void port.getAdminAssignmentDetail(selected.bookingId).then(value=>{if(live)setDetail(value);}).catch(()=>{if(live)setDetailError('Không thể tải lịch sử phân công. Vui lòng thử lại sau');});return()=>{live=false;};},[selected,port]);
 const busyRef=useRef(false);
 const [now,setNow]=useState(()=>Date.now());
 useEffect(()=>{const tick=()=>setNow(Date.now());const timer=setInterval(tick,1000);window.addEventListener('focus',tick);return()=>{clearInterval(timer);window.removeEventListener('focus',tick);};},[]);
 const eligibleRows=rows.filter(row=>Date.parse(row.startAt)>now);
 const started=selected ? !(Date.parse(selected.startAt)>now) : false;
 const load=useCallback(async()=>{setLoading(true);setLoadError('');setGuideError('');const [bookings,candidates]=await Promise.allSettled([port.listAdminQueue(),port.listEligibleGuides()]);if(bookings.status==='fulfilled'){setRows(bookings.value);setSelected(old=>old?bookings.value.find(r=>r.bookingId===old.bookingId)??null:null);}else{setRows([]);setSelected(null);setLoadError('Không thể tải danh sách đơn. Vui lòng thử lại sau');}if(candidates.status==='fulfilled')setGuides(candidates.value);else{setGuides([]);setGuideError('Không thể tải danh sách hướng dẫn viên. Vui lòng thử lại sau');}setLoading(false);},[port]);
 useEffect(()=>{void load();},[load]);
 function choose(row:AdminGuideAssignmentQueueItem){setSelected(row);setGuide(row.guideUserId??'');setError('');setNotice('');}
 async function save(){if(!selected||!guide||busyRef.current)return;if(!(Date.parse(selected.startAt)>Date.now())){setNow(Date.now());setError('Tour đã đến giờ khởi hành, không thể phân công hoặc đổi hướng dẫn viên.');return;}if(guide===selected.guideUserId){setNotice('Giữ nguyên hướng dẫn viên hiện tại.');return;}busyRef.current=true;setBusy(true);setError('');setNotice('');const storageKey=`localens.guide-assignment:${selected.bookingId}:${guide}`;try{let key=sessionStorage.getItem(storageKey);if(!key){key=`guide-assignment-${crypto.randomUUID()}`;sessionStorage.setItem(storageKey,key);}await port.assignGuide({bookingId:selected.bookingId,guideUserId:guide,idempotencyKey:key});sessionStorage.removeItem(storageKey);setNotice('Phân công hướng dẫn viên thành công.');await load();}catch(e){setError(e instanceof RuntimeGuideAssignmentError&&['CONFLICT','NOT_FOUND','SCHEDULE_CONFLICT'].includes(e.code)?'Đơn, lịch khởi hành hoặc hướng dẫn viên không còn đủ điều kiện. Vui lòng tải lại dữ liệu mới nhất.':'Phân công hướng dẫn viên thất bại. Vui lòng thử lại sau');}finally{setBusy(false);busyRef.current=false;}}
 const filtered=eligibleRows.filter(r=>(!kind||(kind==='fixed'?!!r.departureId:!r.departureId))&&(!status||(status==='assigned'?!!r.guideUserId:!r.guideUserId))&&(!lang||r.language===lang)&&(!from||day(r.startAt)>=from)&&(!to||day(r.startAt)<=to)&&[r.bookingId,r.titleVi,r.meetingPoint].join(' ').toLocaleLowerCase('vi').includes(query.trim().toLocaleLowerCase('vi')));
 const pages=Math.max(1,Math.ceil(filtered.length/5)),current=Math.min(page,pages);
 return <div className={`${base.shell} ${s.shell}`}><div className={base.workspace}><div className={base.top}><span>Trang chủ / Phân công hướng dẫn viên</span></div><main className={base.main}><div className={base.heading}><div><h1>Phân công hướng dẫn viên</h1><p>Phân công cho tour cố định và tour cá nhân hóa đã xác nhận, đã thanh toán và còn đủ điều kiện thực hiện.</p></div></div>
 <div className={`${base.metrics} ${s.metrics}`}>{[['','Đủ điều kiện phân công',eligibleRows.length],['unassigned','Chưa phân công',eligibleRows.filter(r=>!r.guideUserId).length],['assigned','Đã phân công',eligibleRows.filter(r=>r.guideUserId).length]].map(([value,label,count])=><button key={String(value)} aria-pressed={status===value} onClick={()=>{setStatus(String(value));setPage(1);}}><Users/><span>{label}<b>{count}</b></span></button>)}</div>
 {notice&&<p role="status" className={base.success}>{notice}</p>}{loadError&&<p role="alert" className={base.error}>{loadError}</p>}{guideError&&<p role="alert" className={base.error}>{guideError}</p>}
 <div className={s.layout}><div><section className={base.card}><h2>Bộ lọc tìm kiếm</h2><div className={s.filters}><label className={base.search}><Search size={18}/><input aria-label="Tìm đơn" placeholder="Mã đơn, tên tour, điểm đón…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><label>Từ ngày<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></label><label>Đến ngày<input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1);}}/></label><select aria-label="Loại tour" value={kind} onChange={e=>{setKind(e.target.value);setPage(1);}}><option value="">Tất cả loại tour</option><option value="fixed">Tour cố định</option><option value="personalized">Tour cá nhân hóa</option></select><select aria-label="Ngôn ngữ phục vụ" value={lang} onChange={e=>{setLang(e.target.value);setPage(1);}}><option value="">Tất cả ngôn ngữ</option><option value="vi">Tiếng Việt</option><option value="en">Tiếng Anh</option></select><select aria-label="Trạng thái phân công" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Tất cả trạng thái</option><option value="unassigned">Chưa phân công</option><option value="assigned">Đã phân công</option></select><button className={base.secondary} onClick={()=>{setQuery('');setKind('');setStatus('');setLang('');setFrom('');setTo('');setPage(1);}}>Đặt lại bộ lọc</button></div></section>
 <section className={base.card}><h2>Danh sách đơn đủ điều kiện phân công</h2>{loading?<p role="status">Đang tải danh sách đơn…</p>:<><div className={base.scroll}><table><thead><tr>{['Mã đơn','Tour / Loại tour','Ngày thực hiện','Điểm đón','Số khách','Ngôn ngữ','HDV hiện tại','Thao tác'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{filtered.slice((current-1)*5,current*5).map(r=><tr key={r.bookingId} className={selected?.bookingId===r.bookingId?s.selected:undefined}><td title={r.bookingId}>{r.bookingId.slice(0,8)}</td><td>{r.titleVi}<small style={{display:'block'}}>{r.departureId?'Tour cố định':'Tour cá nhân hóa'}</small></td><td>{date(r.startAt)}</td><td>{r.meetingPoint}</td><td>{r.partySize}</td><td>{language(r.language)}</td><td>{r.guideDisplayName??'Chưa phân công'}</td><td><button className={base.secondary} disabled={busy} onClick={()=>choose(r)}>Xem và phân công</button></td></tr>)}</tbody></table></div>{!filtered.length&&!loadError&&<p>{eligibleRows.length?'Không có đơn phù hợp.':'Chưa có đơn đủ điều kiện phân công.'}</p>}</>}<div className={base.pagination}><span>{filtered.length} đơn</span><button disabled={current===1} onClick={()=>setPage(current-1)}>Trước</button><span>{current} / {pages}</span><button disabled={current===pages} onClick={()=>setPage(current+1)}>Sau</button></div><button className={base.secondary} disabled={loading||busy} onClick={()=>void load()}>Tải lại dữ liệu</button></section></div>
 <aside>{selected?<><section className={base.card}><h2>Chi tiết đơn được chọn</h2><h3>{selected.titleVi}</h3><dl className={s.facts}>{[['Loại tour',selected.departureId?'Tour cố định':'Tour cá nhân hóa'],['Mã đơn',selected.bookingId],['Khởi hành',date(selected.startAt)],['Kết thúc',date(selected.endAt)],['Điểm đón',selected.meetingPoint],['Số khách',selected.partySize],['Ngôn ngữ phục vụ',language(selected.language)],['Hướng dẫn viên hiện tại',selected.guideDisplayName??'Chưa có'],['Trạng thái đơn','Đã xác nhận'],['Thanh toán','Đã thanh toán'],['Trạng thái lịch',detail?(detail.departureStatus==='sold_out'?'Hết chỗ':detail.departureStatus==='scheduled'?'Đã lên lịch':detail.departureStatus) :detailError?'Chưa có dữ liệu':'Đang tải…']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><h3>Lịch sử phân công</h3>{detailError?<p role={port.getAdminAssignmentDetail?"alert":"note"} className={base.error}>{detailError}</p>:detail?detail.history.length?detail.history.map(h=><p key={h.id} className={base.stop}><b>{h.guide}</b><small>{date(h.assignedAt)} · {({assigned:'Đã phân công',accepted:'Đã nhận lịch',completed:'Đã hoàn thành',closed:'Đã kết thúc'} as Record<string,string>)[h.status]??h.status}</small>{h.closedAt&&<small>Kết thúc: {date(h.closedAt)}</small>}</p>):<p>Chưa có lịch sử phân công.</p>:<p>Đang tải lịch sử…</p>}</section><section className={base.card}><h2>Chọn hướng dẫn viên</h2>{started&&<p>Tour đã đến giờ khởi hành. Chỉ được xem thông tin và lịch sử.</p>}{!guides.length&&!guideError?<p>Không có hướng dẫn viên khả dụng để phân công</p>:guides.map(g=><label className={s.guide} key={g.guideUserId}><input type="radio" name="guide" checked={guide===g.guideUserId} disabled={busy||loading||started} onChange={()=>setGuide(g.guideUserId)}/><span><b>{g.displayName}</b><small>{language(g.language)}</small></span></label>)}{guide&&selected.guideUserId&&guide!==selected.guideUserId&&<p>Hướng dẫn viên mới sẽ thay người đang được phân công sau khi bạn xác nhận.</p>}{error&&<p role="alert" className={base.error}>{error}</p>}<div className={base.actions}><button className={base.secondary} disabled={busy} onClick={()=>{setSelected(null);setGuide('');setError('');}}>Hủy</button><button disabled={!guide||busy||loading||!!guideError||started} onClick={()=>void save()}>{busy?'Đang lưu…':'Xác nhận phân công'}</button></div></section></>:<section className={base.card}><h2>Chi tiết và phân công</h2><p>Chọn một đơn để xem thông tin và phân công hướng dẫn viên.</p></section>}</aside></div></main></div></div>;
}
