'use client';
import { ReviewModal } from '@/components/customer/review-modal';
import {type AdminPrototypeWorkspace} from '@/lib/infrastructure/demo/admin-workspace';
import {type AdminTour} from '@/lib/application/admin-tours';
import { departureLabels,remaining,type Departure } from '@/lib/application/admin-departures';

import { Bell,CalendarDays,CheckCircle,ChevronLeft,ChevronRight,Eye,Flag,House,Info,PlusCircle,RotateCcw,Search,Trash2,Users,XCircle } from 'lucide-react';
import { useEffect,useState } from 'react';
import b from './admin-accounts.module.css';
import s from './admin-departures.module.css';
type Modal={kind:'create'}|{kind:'view'|'cancel';id:string}|null;
export function AdminDepartures({workspace,revision=0}:{workspace:AdminPrototypeWorkspace;revision?:number}){
 const [catalog,setCatalog]=useState<AdminTour[]>([]);
 const [rows,setRows]=useState<Departure[]>([]);
 useEffect(()=>{let active=true;void workspace.tours.list().then(data=>{if(active){setCatalog(data);setRows(workspace.departures());}});return()=>{active=false;};},[workspace,revision]);
 const tours=catalog.filter(t=>t.published).map(t=>({id:t.id,status:t.status,version:`v${t.published!.version}.0`,image:t.published!.imageUrl,translations:{vi:{title:t.published!.name}}}));
 const photo=(i:number)=>tours[i]?.image||'/images/green/saigon-skyline.webp';
 const [tourIndex,setTourIndex]=useState(0),[status,setStatus]=useState(''),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1),[size,setSize]=useState(6),[modal,setModal]=useState<Modal>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [draft,setDraft]=useState({date:'',start:'08:00',end:'13:30',capacity:15});
 if(!tours.length)return <p>Chưa có tour đã xuất bản. Hãy xuất bản tour trước khi tạo lịch.</p>;
 const index=Math.min(tourIndex,tours.length-1);
 const tour=tours[index],all=rows.filter(r=>r.tourId===tour.id),filtered=all.filter(r=>(!status||r.status===status)&&(!from||r.date>=from)&&(!to||r.date<=to)&&tour.translations.vi.title.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi'))),pages=Math.max(1,Math.ceil(filtered.length/size)),currentPage=Math.min(page,pages),visible=filtered.slice((currentPage-1)*size,currentPage*size),selected=modal&&'id'in modal?rows.find(r=>r.id===modal.id):null;
 const reset=()=>{setQuery('');setStatus('');setFrom('');setTo('');setPage(1);};
 const open=(m:Modal)=>{setError('');setModal(m);};
 const badge=(r:Departure)=><span className={`${s.badge} ${s[r.status]}`}>{departureLabels[r.status]}</span>;
 async function save(form:HTMLFormElement){const values=new FormData(form);try{const r:Departure={date:String(values.get("date")),start:String(values.get("start")),end:String(values.get("end")),capacity:Number(values.get("capacity")),id:crypto.randomUUID(),tourId:tour.id,version:tour.version,held:0,booked:0,status:'scheduled'};if(rows.some(x=>x.tourId===r.tourId&&x.date===r.date&&x.start===r.start&&x.status!=='cancelled'))throw Error('Tour đã có lịch khởi hành vào thời điểm này');await workspace.create(r);setRows(workspace.departures());reset();setModal(null);setNotice('Tạo lịch khởi hành thành công');}catch(e){setError((e as Error).message);}}
 return <div className={`${b.shell} ${s.shell}`}>
 <div className={s.main}><div className={s.header}><label><Search size={20}/><input aria-label="Tìm tour" placeholder="Tìm kiếm tour..." value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><Bell color="#00806b"/></div><div className={s.layout}><main><p className={s.crumb}>Trang chủ › Quản lý lịch khởi hành</p><div className={s.title}><div><h1>Quản lý lịch khởi hành</h1><p>Tạo, xem, tra cứu, theo dõi và hủy lịch khởi hành của tour cố định.</p></div><button className={s.primary} disabled={tour.status!=='published'} onClick={()=>{setDraft({date:'',start:'08:00',end:'13:30',capacity:15});open({kind:'create'});}}><PlusCircle/>Thêm lịch khởi hành</button></div>
 <section className={s.tour}><img src={photo(index)} alt={tour.translations.vi.title}/><div><small>Tour đang xem:</small><h2>{tour.translations.vi.title}</h2><span className={`${s.badge} ${s.scheduled}`}>{tour.version} · {tour.status==='published'?'Đã xuất bản':'Đã lưu trữ'}</span></div><label>Thay đổi tour<select aria-label="Thay đổi tour" value={index} onChange={e=>{setTourIndex(Number(e.target.value));reset();setNotice('');}}>{tours.map((t,i)=><option key={t.id} value={i}>{t.translations.vi.title}</option>)}</select></label></section>
 <div className={s.metrics}>{[['','Tổng lịch',CalendarDays],['scheduled','Đã lên lịch',CheckCircle],['sold_out','Hết chỗ',Users],['cancelled','Đã hủy',XCircle],['completed','Đã hoàn thành',Flag]].map(([key,label,Icon])=>{const I=Icon as typeof House;return <button key={String(key)} onClick={()=>{setStatus(String(key));setPage(1);}}><I/><span>{String(label)}<strong>{key?all.filter(r=>r.status===key).length:all.length}</strong></span></button>;})}</div>
 {notice&&<p className={s.notice} role="status">{notice}</p>}<section className={s.card}><h2>Danh sách lịch khởi hành</h2><div className={s.filters}><label>Từ ngày<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></label><label>Đến ngày<input type="date" min={from} value={to} onChange={e=>{setTo(e.target.value);setPage(1);}}/></label><select aria-label="Trạng thái lịch" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Tất cả trạng thái</option>{Object.entries(departureLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button onClick={reset}><RotateCcw size={17}/>Đặt lại</button></div><div className={s.table}><table><thead><tr>{['#','Tour','Phiên bản','Ngày khởi hành','Bắt đầu','Kết thúc','Tổng chỗ','Chỗ giữ','Đã đặt','Còn lại','Trạng thái','Thao tác'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map((r,i)=><tr key={r.id}><td>{(currentPage-1)*size+i+1}</td><td><div className={s.tourCell}><img src={photo(index)} alt=""/>{tour.translations.vi.title}</div></td><td>{r.version}</td><td>{r.date.split('-').reverse().join('/')}</td><td>{r.start}</td><td>{r.end}</td><td>{r.capacity}</td><td>{r.held}</td><td>{r.booked}</td><td>{remaining(r)}</td><td>{badge(r)}</td><td><div className={s.actions}><button aria-label={`Xem chi tiết ${r.date}`} onClick={()=>open({kind:'view',id:r.id})}><Eye size={16}/>Xem chi tiết</button>{['scheduled','sold_out'].includes(r.status)&&<button className={s.danger} aria-label={`Hủy lịch ${r.date}`} onClick={()=>open({kind:'cancel',id:r.id})}><Trash2 size={15}/>Hủy lịch</button>}</div></td></tr>)}</tbody></table></div>{!visible.length&&<p className={s.empty}>Không có lịch khởi hành phù hợp</p>}<footer className={s.pagination}><span>{filtered.length?`Hiển thị ${(currentPage-1)*size+1}–${Math.min(currentPage*size,filtered.length)} trong tổng số ${filtered.length} lịch`:'0 lịch khởi hành'}</span><button aria-label="Trang trước" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={18}/></button><strong>{currentPage} / {pages}</strong><button aria-label="Trang sau" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}><ChevronRight size={18}/></button><select aria-label="Số dòng mỗi trang" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1);}}>{[6,10,20].map(n=><option key={n} value={n}>{n} dòng/trang</option>)}</select></footer></section><div className={s.note}><Info/><p><strong>Cách tính số chỗ còn lại</strong><br/>Tổng số chỗ − chỗ tạm giữ còn hiệu lực − số chỗ đã đặt hợp lệ. Lịch đã hủy hoặc hoàn thành không nhận đặt chỗ mới.</p></div></main>
 <aside className={s.attention}><h2><Bell color="#f5a000"/>Lịch cần chú ý</h2>{all.filter(r=>r.status==='sold_out'||(r.status==='scheduled'&&remaining(r)<=4)).slice(0,3).map(r=><button key={r.id} onClick={()=>open({kind:'view',id:r.id})}><img src={photo(index)} alt=""/><span><small>{r.date} · {r.start}</small><strong>{tour.translations.vi.title}</strong>{badge(r)}<small>Còn {remaining(r)} / {r.capacity} chỗ</small></span></button>)}</aside></div></div>
 {modal&&<ReviewModal title={modal.kind==='create'?'Thêm lịch khởi hành':modal.kind==='cancel'?'Xác nhận hủy lịch':'Chi tiết lịch khởi hành'} closeLabel="Đóng hộp thoại" busy={false} onClose={()=>setModal(null)}><p>{tour.translations.vi.title} · v1.0 đã xuất bản</p>{error&&<p role="alert">{error}</p>}{modal.kind==='create'?<form className={s.form} onSubmit={e=>{e.preventDefault();save(e.currentTarget);}}><label>Ngày khởi hành<input required name="date" type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Giờ bắt đầu<input required name="start" type="time" value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})}/></label><label>Giờ kết thúc dự kiến<input required name="end" type="time" value={draft.end} onChange={e=>setDraft({...draft,end:e.target.value})}/></label><label>Tổng số chỗ<input required name="capacity" type="number" min="1" max="1000" step="1" value={draft.capacity} onChange={e=>setDraft({...draft,capacity:Number(e.target.value)})}/></label><button className={s.primary} type="submit">Lưu</button></form>:selected&&<><dl className={s.details}>{[['Ngày khởi hành',selected.date],['Giờ bắt đầu / kết thúc',`${selected.start} – ${selected.end}`],['Tổng số chỗ',selected.capacity],['Chỗ đang tạm giữ',selected.held],['Chỗ đã đặt',selected.booked],['Số chỗ còn lại',remaining(selected)],['Trạng thái',departureLabels[selected.status]]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{modal.kind==='cancel'?<><p>Lịch sẽ ngừng nhận đặt chỗ, giải phóng chỗ tạm giữ và được giữ lại để tra cứu lịch sử. Trong bản demo này, các đơn liên quan không bị sửa.</p><div className={s.actions}><button onClick={()=>setModal(null)}>Quay lại</button><button className={s.danger} onClick={()=>{try{workspace.cancel(selected.id);setRows(workspace.departures());setModal(null);setNotice('Đã hủy lịch khởi hành. Dữ liệu lịch sử được giữ nguyên.');}catch(e){setError((e as Error).message);}}}>Xác nhận hủy</button></div></>:<p>Thông tin lịch chỉ xem. Nếu cần thay đổi ngày giờ hoặc sức chứa, hãy tạo lịch mới.</p>}</>}</ReviewModal>}</div>;
}
